Repository hmcts/et-ccd-callbacks, pull requests merged in 2022-11, with the labels that each got.

#532 RET-2323: CR: Add validation to the disposal date field at jurisdiction level
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-532

#537 RET-2612: Added ccdId to rejected email template
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/UploadDocumentController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-537

#540 Ret-2793
  bin/import-ccd-definition-zsh.sh
Labels: ns:et, prd:et, rel:et-cos-pr-540

#545 RET-2685: Prefilling 'is hearing already listed'
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-545

#547 RET-2590: Add a suggested hearing venue field to the case details tab
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-547

#550 Ret 2639 - refactor code to match specification
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/ReferralTypeData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-550

#552 Ret 2639 hotfix - fix bug in referral document tests cause by hardcoded date
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-552

#551 Updated ET3 Notification templates
  charts/et-cos/Chart.yaml
  charts/et-cos/values.preview.template.yaml
  charts/et-cos/values.yaml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3NotificationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3NotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingService.java
  src/main/resources/application.properties
  src/test/integration/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NotificationHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-551

#560 ACAS email corrected
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-560

#557 Sub multiple field in case data
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelReadingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleBatchUpdate2Service.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleUploadService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelReadingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-557

#562 Ret 2736 branch fix
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  bin/run-crossbrowser-tests.sh
  build.gradle
  package.json
  src/test/crossbrowser/supportedBrowsers.js
  src/test/end-to-end/codecept.conf.js
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/helpers/saucelabsHelper.js
  src/test/end-to-end/pages/amendCaseDetails/amendCaseDetails.js
  src/test/end-to-end/pages/amendCaseDetails/amendCaseDetailsWithCasePosition.js
  src/test/end-to-end/pages/amendClaimantDetails/amendClaimantDet.js
  src/test/end-to-end/pages/amendClaimantRepresentative/amendClaimantRepresentative.js
  src/test/end-to-end/pages/amendRespondentDetails/amendRespondentDetails.js
  src/test/end-to-end/pages/amendRespondentRepresentative/amendRespondentRepresentative.js
  src/test/end-to-end/pages/broughtForward/broughtForward.js
  src/test/end-to-end/pages/createCase/caseApplication.js
  src/test/end-to-end/pages/createCase/caseClaimantIsWA.js
  src/test/end-to-end/pages/createCase/caseClaimantType.js
  src/test/end-to-end/pages/createCase/caseClaimantWA.js
  src/test/end-to-end/pages/createCase/caseDate.js
  src/test/end-to-end/pages/createCase/caseHearingPref.js
  src/test/end-to-end/pages/createCase/caseJur.js
  src/test/end-to-end/pages/createCase/caseList.js
  src/test/end-to-end/pages/createCase/caseOther.js
  src/test/end-to-end/pages/createCase/caseRep.js
  src/test/end-to-end/pages/createCase/caseResp.js
  src/test/end-to-end/pages/nextStep/nextStep.js
  src/test/end-to-end/paths/loginUser.js
  src/test/end-to-end/paths/moveAcceptedCaseToCaseCloseStateErrorCheck.js
  src/test/end-to-end/paths/verifyBFAction.js
  src/test/end-to-end/paths/verifyCaseDetails.js
  src/test/end-to-end/paths/verifyClaimantDetails.js
  src/test/end-to-end/paths/verifyClaimantRepresentative.js
  src/test/end-to-end/paths/verifyCreateCase.js
  src/test/end-to-end/paths/verifyRespondentDetails.js
  src/test/end-to-end/paths/verifyRespondentRepresentative.js
  src/test/end-to-end/saucelabs.conf.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-562
