Repository hmcts/et-ccd-callbacks, pull requests merged in 2022-05, with the labels that each got.

#231 RET-862
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/AddSingleCaseToMultipleService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationMidEventValidationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/bulkaddsingles/BulkAddSinglesValidator.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/bulkaddsingles/SingleCasesValidator.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MultipleUtil.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/AddSingleCaseToMultipleServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationMidEventValidationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/bulkaddsingles/BulkAddSinglesValidatorTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/bulkaddsingles/SingleCasesValidatorTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-231

#214 PI25 IP
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/casesawaitingjudgment/CasesAwaitingJudgmentReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/casesawaitingjudgment/ElasticSearchQuery.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/eccreport/EccReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/eccreport/EccReportCcdDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/eccreport/EccReportElasticSearchQuery.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentsReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentsReportElasticSearchQuery.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/servingclaims/ServingClaimsReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysCcdReportDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysElasticSearchQuery.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysReportDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/timetofirsthearing/TimeToFirstHearingReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/AddSingleCaseToMultipleService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationMidEventValidationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/bulkaddsingles/BulkAddSinglesValidator.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/bulkaddsingles/SingleCasesValidator.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MultipleUtil.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/casesawaitingjudgment/CasesAwaitingJudgmentReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/eccreport/EccReportCaseDataBuilder.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/eccreport/EccReportCcdReportDataSourceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/eccreport/EccReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentReportElasticSearchQueryTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentsReportCcdReportDataSourceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentsReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/servingclaims/ServingClaimsReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysCcdReportDataSourceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/timetofirsthearing/TimeToFirstHearingReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/AddSingleCaseToMultipleServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationMidEventValidationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/bulkaddsingles/BulkAddSinglesValidatorTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/bulkaddsingles/SingleCasesValidatorTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-214

#238 Bump et-data-model to 1.0.2, et-common to 0.0.31
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-238

#236 RET-1764
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/casesawaitingjudgment/CasesAwaitingJudgmentReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/casescompleted/CasesCompletedReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/casesourcelocalreport/CaseSourceLocalReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/claimsbyhearingvenue/ClaimsByHearingVenueReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/eccreport/EccReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingstojudgments/HearingsToJudgmentsReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentsReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/servingclaims/ServingClaimsReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/timetofirsthearing/TimeToFirstHearingReport.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/timetofirsthearing/TimeToFirstHearingReportTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-236

#247 RET-823
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListingGenerationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReferenceServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ClaimsByHearingVenueExcelReportDocumentInfoServiceTest.java
  src/test/resources/caseDetailsTest1.json
  src/test/resources/exampleListingV1.json
Labels: ns:et, prd:et, rel:et-cos-pr-247

#251 Update renovate.json
  .github/dependabot.yml
  renovate.json
Labels: ns:et, prd:et, rel:et-cos-pr-251

#245 Update how ethos case references are generated
  Jenkinsfile_CNP
  README.md
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/config/QueueClientConfiguration.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/MultipleRefEnglandWalesRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/MultipleRefRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/MultipleRefScotlandRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/SingleRefEnglandWalesRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/SingleRefRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/SingleRefScotlandRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/SubMultipleRefEnglandWalesRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/SubMultipleRefRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/SubMultipleRefScotlandRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkSearchService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseCreationForCaseWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/MultipleReferenceService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SingleReferenceService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SubMultipleReferenceService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationService.java
  src/main/resources/application-dev.properties
  src/main/resources/db/dev/V003.1__DevReferenceData.sql
  src/main/resources/db/migration/V001__CaseRefTables.sql
  src/main/resources/db/migration/V002__CaseRefTableData.sql
  src/main/resources/db/migration/V002__SingleCaseRefFunction.sql
  src/main/resources/db/migration/V003__MultipleCaseRefFunction.sql
  src/main/resources/db/migration/V003__ReferenceDataTables.sql
  src/main/resources/db/migration/V004__EnglandWalesSingleCaseRefFunction.sql
  src/main/resources/db/migration/V004__SubMultipleCaseRefFunction.sql
  src/main/resources/db/migration/V005__CaseRefTableData.sql
  src/main/resources/db/migration/V005__ScotlandSingleCaseRefFunction.sql
  src/main/resources/db/migration/V006__EnglandWalesMultipleCaseRefFunction.sql
  src/main/resources/db/migration/V007__AddEmpStatusUnknown.sql
  src/main/resources/db/migration/V007__ScotlandMultipleCaseRefFunction.sql
  src/main/resources/db/migration/V008__EmpStatusCast.sql
  src/main/resources/db/migration/V008__EnglandWalesSubMultipleCaseRefFunction.sql
  src/main/resources/db/migration/V009__ScotlandSubMultipleCaseRefFunction.sql
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/config/MockServiceBus.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/MultipleRefEnglandWalesRepositoryTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/MultipleRefScotlandRepositoryTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/SingleRefEnglandWalesRepositoryTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/SingleRefScotlandRepositoryTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseCreationForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/MultipleReferenceServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SingleReferenceServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SubMultipleReferenceServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/EtCosPostgresqlContainer.java
  src/test/resources/application.properties
Labels: ns:et, prd:et, rel:et-cos-pr-245

#256 Remove flyway migrations from Jenkins pipeline
  Jenkinsfile_CNP
Labels: ns:et, prd:et, rel:et-cos-pr-256

#257 Merge master
  .github/dependabot.yml
  build.gradle
  renovate.json
Labels: ns:et, prd:et, rel:et-cos-pr-257

#261 Update dev reference data flyway migration
  src/main/resources/db/dev/V003.1__DevReferenceData.sql
Labels: ns:et, prd:et, rel:et-cos-pr-261

#258 RET-1779
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/clerk/ClerkController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/admin/AdminData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/admin/CCDCallbackResponse.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/admin/types/ClerkAdd.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/CourtWorkerRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/clerk/ClerkAddService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/clerk/ClerkControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/clerk/ClerkAddServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/AdminDataBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-258

#260 RET-1783
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/employeemember/EmployeeMemberController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/admin/AdminData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/admin/types/EmployeeMember.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/CourtWorkerRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/employeemember/EmployeeMemberService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/employeemember/EmployeeMemberControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/employeemember/EmployeeMemberServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/AdminDataBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-260

#267 Suppress netty CVEs
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-267

#268 Bump et libs
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-268

#237 Update for using RSE IdAM Simulator
  src/main/resources/application-dev.properties
Labels: ns:et, prd:et, rel:et-cos-pr-237

#266 RET-1786
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/CourtWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/courtworker/CourtWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/admin/AdminData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/CourtWorkerRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/CourtWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/courtworker/CourtWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/CourtWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/courtworker/CourtWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/CourtWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/courtworker/CourtWorkerServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-266

#273 Fix SwaggerUI timeout
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/AllocateHearingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferMultiplesController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/CreateController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/StaffImportController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/courtworker/CourtWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/judge/JudgeController.java
  src/main/resources/application.properties
Labels: ns:et, prd:et, rel:et-cos-pr-273

#275 Ret 1865
  README.md
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/AllocateHearingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferMultiplesController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/CreateController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/filelocation/FileLocationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/StaffImportController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/judge/JudgeController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/admin/AdminData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/FileLocationRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/filelocation/FileLocationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/filelocation/SaveFileLocationException.java
  src/main/resources/application.properties
  src/test/integration/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/EtCosPostgresqlContainer.java
  src/test/integration/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/MultipleRefEnglandWalesRepositoryTest.java
  src/test/integration/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/MultipleRefScotlandRepositoryTest.java
  src/test/integration/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/SingleRefEnglandWalesRepositoryTest.java
  src/test/integration/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/SingleRefScotlandRepositoryTest.java
  src/test/integration/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/filelocation/FileLocationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/filelocation/FileLocationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/AdminDataBuilder.java
  src/test/resources/application.properties
Labels: ns:et, prd:et, rel:et-cos-pr-275
