Repository hmcts/et-ccd-callbacks, pull requests merged in 2022-03, with the labels that each got.

#125 Merge ECM R5.0.25
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ExcelActionsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/referencedata/JudgeEmploymentStatus.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/JudgeRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ECCHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UpdateDataModelBuilder.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReportData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReportDoc.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingstojudgments/HearingsToJudgmentsReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/servingclaims/ServingClaimsReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysCcdReportDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysElasticSearchQuery.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysReportData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysReportDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysReportDetail.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysReportParams.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysReportSummary.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysReportSummary2.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/FixMultipleCaseApiService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/JudgeSelectionService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/referencedata/JudgeService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/referencedata/jpaservice/JpaJudgeService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ExcelActionsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReportDocTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingstojudgments/HearingsToJudgmentsReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentsReportCaseDataBuilder.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/servingclaims/ServingClaimsReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysCaseDataBuilder.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysCcdReportDataSourceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/FixMultipleCaseServiceApiTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/JudgeSelectionServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/referencedata/jpaservice/JpaJudgeServiceTest.java
  src/test/resources/bfActionReportDocTestDateRangeResource.json
  src/test/resources/bfActionReportDocTestSingleDateResource.json
  src/test/resources/reportDetailsTestClaimsServed.json
  src/test/resources/servingClaimsAllDaysEntries.json
  src/test/resources/servingClaimsDay6EntriesSorted.json
  src/test/resources/sessionDaysExpected.json
Labels: ns:et, prd:et, rel:et-cos-pr-125

#126 Jenkins nightly pipeline changes
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-cos-pr-126

#131 Bump base java chart to 3.7.3
  charts/et-cos/Chart.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-131

#141 Bump Spring Boot to 2.6.4
  build.gradle
  charts/et-cos/Chart.yaml
  charts/et-cos/values.preview.template.yaml
  charts/et-cos/values.yaml
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/AllocateHearingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/BulkActionsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/BulkAddSinglesController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferMultiplesController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/DocumentGenerationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ExcelActionsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/HearingDetailsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListHearingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListingGenerationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/MultipleDocGenerationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PersistentQueueActionsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReferenceDataController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/VerifyTokenService.java
  src/main/resources/application.properties
  src/main/resources/bootstrap.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-141

#142 Fix CVEs
  config/owasp/suppressions.xml
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-142

#144 Add JUnit vintage engine to enable JUnit 4 tests with Spring Boot 2.6.4
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-144

#149 Merge ECM R5.0.26
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/BulkActionsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/BulkAddSinglesController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/DocumentGenerationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ExcelActionsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListingGenerationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/MultipleDocGenerationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PersistentQueueActionsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReferenceDataController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/dynamiclists/DynamicJudgements.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/Constants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/ReportParams.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/eccreport/EccReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/eccreport/EccReportCcdDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/eccreport/EccReportData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/eccreport/EccReportDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/eccreport/EccReportDetail.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/eccreport/EccReportElasticSearchQuery.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaySummaryItem.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReportData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReportDetail.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReportDoc.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentsReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/servingclaims/ServingClaimsReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/casetransfer/CaseTransferUtils.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleTransferService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DynamicListHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MultipleUtil.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/eccreport/EccReportCaseDataBuilder.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/eccreport/EccReportCcdReportDataSourceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/eccreport/EccReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReportDocTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentsReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/servingclaims/ServingClaimsReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysCaseDataBuilder.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleTransferServiceTest.java
  src/test/resources/eccExpected.json
Labels: ns:et, prd:et, rel:et-cos-pr-149

#158 Add UNKNOWN emp_status value
  build.gradle
  config/owasp/suppressions.xml
  package.json
  src/main/resources/db/migration/V007__AddEmpStatusUnknown.sql
  src/main/resources/db/migration/V008__EmpStatusCast.sql
Labels: ns:et, prd:et, rel:et-cos-pr-158

#162 Bump versions
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-162

#164 Update yarn.lock for minimist
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-164

#168 Merge ECM R5.0.27
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/letters/InvalidCharacterCheck.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeCcdReportDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeElasticSearchQuery.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeReportData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeReportDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeReportDetail.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeReportSummary.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeReportSummary2.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeReportSummary2Hdr.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeReportSummaryHdr.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/ReportFields.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeCcdDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeElasticSearchQuery.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseCloseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleAmendLeadCaseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeCaseDataBuilder.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeCcdReportDataSourceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeReportTests.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseCloseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataServiceTest.java
  src/test/resources/hearingsByHearingTypeExpected.json
Labels: ns:et, prd:et, rel:et-cos-pr-168
