Repository hmcts/et-ccd-callbacks, pull requests merged in 2022-10, with the labels that each got.

#509 DO NOT MERGE: R1.0.3
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/config/NotificationsConfig.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CloseReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/InitialConsiderationData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/BulkHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ECCHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et1VettingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/InitialConsiderationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralStatus.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/timetofirsthearing/TimeToFirstHearingReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkSearchService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkUpdateService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EmailService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationService.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/end-to-end/pages/createCase/caseDate.js
  src/test/integration/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CloseReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/CreateControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/BulkHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/EmailServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkCreationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkSearchServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SubMultipleServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CCDRequestBuilder.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDataBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-509

#513 Merge 1.0.3 into R1.1
  Jenkinsfile_nightly
  build.gradle
  config/owasp/suppressions.xml
  package.json
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/config/NotificationsConfig.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CloseReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/test/end-to-end/pages/createCase/caseDate.js
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CloseReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/EmailServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-513

#515 Ret 2516
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
Labels: ns:et, prd:et, rel:et-cos-pr-515

#518 RET-2612: Email on case rejection document upload
  build.gradle
  charts/et-cos/Chart.yaml
  charts/et-cos/values.preview.template.yaml
  charts/et-cos/values.yaml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/UploadDocumentController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelper.java
  src/main/resources/application-cftlib.properties
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/integration/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/UploadDocumentControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-518

#514 Update application-dev.properties
  src/main/resources/application-dev.properties
Labels: ns:et, prd:et, rel:et-cos-pr-514

#510 Fixes from ECM R5.0.41
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/BFHelper.java
  src/main/resources/venueAddressValues.yml
  src/test/resources/venueAddressValues.yml
Labels: ns:et, prd:et, rel:et-cos-pr-510

#520 RET-2676: CR for Referral Emails
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-520

#521 RET-0000: Fix tests on Windows
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReportDocTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-521

#522 RET-1856: Added submitted callback
  charts/et-cos/Chart.yaml
  charts/et-cos/values.preview.template.yaml
  charts/et-cos/values.yaml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingService.java
  src/main/resources/application-cftlib.properties
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/integration/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NotificationHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ServingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDataBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-522

#528 RET-2063: ET3 Notification complete callback
  charts/et-cos/Chart.yaml
  charts/et-cos/values.preview.template.yaml
  charts/et-cos/values.yaml
  package.json
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3NotificationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3NotificationService.java
  src/main/resources/application-cftlib.properties
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/integration/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3NotificationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ServingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-528

#530 RET-2687: Removed 'What Happens Next' section from Initial Consideration complete
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-530

#531 Merge master into r1.1
  config/owasp/suppressions.xml
  src/main/resources/application-dev.properties
  src/test/end-to-end/helpers/etCaseHepler.js
Labels: ns:et, prd:et, rel:et-cos-pr-531
