Repository hmcts/et-ccd-callbacks, pull requests merged in 2022-04, with the labels that each got.

#150 Enable judge data to be imported
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/CreateController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/StaffImportController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/admin/AdminData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/admin/CCDCallbackResponse.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/admin/CCDRequest.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/admin/CaseDetails.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/admin/types/Document.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/admin/types/ImportFile.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/referencedata/CourtWorker.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/referencedata/Judge.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ClerkService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/ImportStrategy.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/AbstractCourtWorkerRowHandler.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/ClerkRowHandler.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/EmployeeMemberRowHandler.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/EmployerMemberRowHandler.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/JudgeRowHandler.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/OfficeSheet.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/RowHandler.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/RowHandlerImportStrategy.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/SheetHandler.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/SimpleSheetHandler.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/StaffDataRowHandler.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/StaffRowHandler.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/StaffImportService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/StaffImportStrategy.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/AllocateHearingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/ScotlandAllocateHearingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/referencedata/CourtWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/referencedata/jpaservice/JpaCourtWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/referencedata/selection/CourtWorkerSelectionService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/referencedata/selection/JudgeSelectionService.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/AllocateHearingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/CreateControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/StaffImportControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/broughtforward/BroughtForwardInitialiserTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ClerkServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/ClerkRowHandlerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/EmployeeMemberRowHandlerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/EmployerMemberRowHandlerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/JudgeRowHandlerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/RowHandlerImportStrategyTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/SimpleSheetHandlerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/StaffDataRowHandlerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/TestSheetHandler.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/StaffImportServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/AllocateHearingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/ScotlandAllocatedHearingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/referencedata/jpaservice/JpaCourtWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/referencedata/selection/CourtWorkerSelectionServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/referencedata/selection/JudgeSelectionServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/AdminDataBuilder.java
  src/test/resources/admin/StaffImportFile.xlsx
Labels: ns:et, prd:et, rel:et-cos-pr-150

#180 Bump versions
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-180

#182 Fix CVEs
  build.gradle
  config/owasp/suppressions.xml
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-182

#178 Enable import of venue reference data
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/AllocateHearingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListHearingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/venues/VenueImportController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/admin/AdminData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/admin/types/VenueImport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/referencedata/Room.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/referencedata/Venue.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/FixedListMappings.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/FixedListSheetImporter.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/FixedListSheetReader.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/FixedListSheetReaderException.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/RoomRowHandler.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/VenueFixedListSheetImporter.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/VenueRowHandler.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/StaffImportService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/venues/VenueImportService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/AllocateHearingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/RoomSelectionService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/ScotlandAllocateHearingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/VenueSelectionService.java
  src/main/resources/fixedListMappings.yml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/AllocateHearingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/venues/VenueImportControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/FixedListSheetReaderTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/RoomRowHandlerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/VenueFixedListSheetImporterTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/VenueRowHandlerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/venues/VenueImportServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/AllocateHearingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/RoomSelectionServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/ScotlandAllocatedHearingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/AdminDataBuilder.java
  src/test/resources/admin/StaffImportFile.xlsx
  src/test/resources/admin/VenuesImportFile.xlsx
Labels: ns:et, prd:et, rel:et-cos-pr-178

#202 RET-927,928 and checkstyle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/casesourcelocalreport/CaseSourceLocalReport.java
  src/test/functional/java/uk/gov/hmcts/ethos/replacement/functional/util/TestUtil.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/CaseSourceLocalReportTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-202

#193 RET-884 Fix Hearings by Hearing Type Report for England/Wales
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeCcdReportDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeElasticSearchQuery.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeReport.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeReportTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-193

#204 Enable file locations to be imported
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/referencedata/FileLocation.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/FileLocationRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/FileLocationFixedListSheetImporter.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/FileLocationRowHandler.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/FixedListSheetReader.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/venues/VenueImportService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/FileLocationFixedListSheetImporterTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/FileLocationRowHandlerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/FixedListSheetReaderTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/VenueFixedListSheetImporterTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/StaffImportServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/venues/VenueImportServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-204

#208 RET-920
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeCcdDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeElasticSearchQuery.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeCcdDataSourceTests.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeReportTests.java
Labels: ns:et, prd:et, rel:et-cos-pr-208

#205 RET-1064 Cases Completed Report for Scotland shows blank Office
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/casescompleted/CasesCompletedReport.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/casescompleted/CaseCompletedReportTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-205

#209 RET-886
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/timetofirsthearing/TimeToFirstHearingReport.java
Labels: ns:et, prd:et, rel:et-cos-pr-209

#203 PI25 - Sprint 6
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListingGenerationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/referencedata/FileLocation.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/FileLocationRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/casescompleted/CasesCompletedReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/casesourcelocalreport/CaseSourceLocalReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeCcdReportDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeElasticSearchQuery.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeCcdDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeElasticSearchQuery.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/timetofirsthearing/TimeToFirstHearingReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/FileLocationFixedListSheetImporter.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/FileLocationRowHandler.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/FixedListSheetReader.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/venues/VenueImportService.java
  src/test/functional/java/uk/gov/hmcts/ethos/replacement/functional/util/TestUtil.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListingGenerationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/CaseSourceLocalReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/casescompleted/CaseCompletedReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeCcdDataSourceTests.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeReportTests.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/FileLocationFixedListSheetImporterTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/FileLocationRowHandlerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/FixedListSheetReaderTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/VenueFixedListSheetImporterTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/StaffImportServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/venues/VenueImportServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-203

#216 RET-878 Fix Brought Forward Report for England/Wales
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReport.java
Labels: ns:et, prd:et, rel:et-cos-pr-216

#215 RET-925 Fix Cases Awaiting Judgment report
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/casesawaitingjudgment/CasesAwaitingJudgmentReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/casesawaitingjudgment/ElasticSearchQuery.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/casesawaitingjudgment/CasesAwaitingJudgmentReportTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-215

#219 RET-886
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/timetofirsthearing/TimeToFirstHearingReport.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/timetofirsthearing/TimeToFirstHearingReportTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-219

#218 Fix office in ECC report header when no cases found
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-218

#220 RET-1738 Fix Serving Claims Report
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/servingclaims/ServingClaimsReport.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/servingclaims/ServingClaimsReportTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-220

#224 RET-1734
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysCcdReportDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysElasticSearchQuery.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysReportDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysCcdReportDataSourceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysReportTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-224

#227 RET-1760
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-227

#228 Fix live caseload report office
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-228
