Repository hmcts/et-ccd-callbacks, pull requests merged in 2022-02, with the labels that each got.

#83 Ret 828: post et-common update changes
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/VenueAddressReaderService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/ScotlandAllocateHearingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseUpdateForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/VenueAddressReaderServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/ResourceLoader.java
  src/test/resources/listingDetailsTest5.json
  src/test/resources/submitEvents1.json
Labels: ns:et, prd:et, rel:et-cos-pr-83

#84 Add et-data-model dependency
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-84

#85 Fix Cases Completed Report for Scotland
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-85

#89 Ret 887 fix hearings to judgment report
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListingGenerationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/Constants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/ReportException.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingstojudgments/HearingsToJudgmentsCaseData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingstojudgments/HearingsToJudgmentsCcdDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingstojudgments/HearingsToJudgmentsDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingstojudgments/HearingsToJudgmentsElasticSearchQuery.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingstojudgments/HearingsToJudgmentsReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingstojudgments/HearingsToJudgmentsReportData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingstojudgments/HearingsToJudgmentsReportDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingstojudgments/HearingsToJudgmentsSearchResult.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingstojudgments/HearingsToJudgmentsSubmitEvent.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeCcdDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeReportData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListingGenerationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingstojudgments/HearingsToJudgmentsCaseDataBuilder.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingstojudgments/HearingsToJudgmentsCcdDataSourceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingstojudgments/HearingsToJudgmentsReportDataTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingstojudgments/HearingsToJudgmentsReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeReportDataTests.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-89

#99 Merge CVE fixes
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-99

#100 Bump versions
  build.gradle
  charts/et-cos/Chart.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-100

#105 Merge master
  build.gradle
  charts/et-cos/Chart.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-105

#93 Fix Brought Forward report clerk parameter
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListingGenerationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/CourtWorkerRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/broughtforward/BroughtForwardInitialiser.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ClerkService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/GenerateReportService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/referencedata/CourtWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/referencedata/jpaservice/JpaCourtWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListingGenerationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/broughtforward/BroughtForwardInitialiserTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ClerkServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/GenerateReportServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/referencedata/jpaservice/JpaCourtWorkerServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-93

#95 Ret 824: Removed unused constants
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/MultipleReferenceService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SingleReferenceService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SubMultipleReferenceService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseUpdateForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentGenerationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/MultipleReferenceServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SingleReferenceServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-95

#112 Merge master into release
  build.gradle
  charts/et-cos/Chart.yaml
  charts/et-cos/values.yaml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/DocumentGenerationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListingGenerationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/dynamiclists/DynamicJudgements.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/letters/InvalidCharacterCheck.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/Constants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentsReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentsReportCcdDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentsReportData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentsReportDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentsReportDetail.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentsReportElasticSearchQuery.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentsReportParams.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentsReportSummary.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FixCaseApiService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/MultipleReferenceService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SingleReferenceService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SubMultipleReferenceService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/letters/InvalidCharacterCheckTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentsReportCaseDataBuilder.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentsReportCcdReportDataSourceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentsReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseUpdateForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentGenerationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FixCaseApiServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/MultipleReferenceServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SingleReferenceServiceTest.java
  src/test/resources/respondentsReportExpected.json
Labels: ns:et, prd:et, rel:et-cos-pr-112
