Repository hmcts/et-ccd-callbacks, pull requests merged in 2022-09, with the labels that each got.

#440 Ret 2185 2
  .gitignore
  build.gradle
  charts/et-cos/Chart.yaml
  charts/et-cos/values.preview.template.yaml
  charts/et-cos/values.yaml
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/config/NotificationsConfig.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EmailService.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/integration/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CloseReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/CreateControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EmailServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-440

#453 Fix snakeyaml CVE
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-453

#457 RET-2185: Added template id to preview env
  charts/et-cos/values.preview.template.yaml
  charts/et-cos/values.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-457

#456 Create APIs with Stub Information
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/external/AcasController.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/external/AcasControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-456

#459 Update Chart.yaml
  charts/et-cos/Chart.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-459

#461 Notify chart
  charts/et-cos/Chart.yaml
  charts/et-cos/values.preview.template.yaml
  charts/et-cos/values.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-461

#462 Update Chart.yaml
  charts/et-cos/Chart.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-462

#464 Merge ECM 5.0.37 functional UI tests
  Jenkinsfile_nightly
  src/test/config.js
  src/test/end-to-end/data/ccd-accept-case.json
  src/test/end-to-end/data/commonConfig.json
  src/test/end-to-end/data/fileUpload.txt
  src/test/end-to-end/helpers/PuppeteerHelper.js
  src/test/end-to-end/helpers/WebDriverHelper.js
  src/test/end-to-end/helpers/accessibility.js
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/helpers/idamApi.js
  src/test/end-to-end/helpers/utils.js
  src/test/end-to-end/pages/acceptanceCase/acceptCase.js
  src/test/end-to-end/pages/acceptanceCase/rejectCase.js
  src/test/end-to-end/pages/amendHearing/hearingListedInWeekend.js
  src/test/end-to-end/pages/broughtForward/bfActionsOutstandingError.js
  src/test/end-to-end/pages/caseTransfer/caseTransfer.js
  src/test/end-to-end/pages/common/constants.js
  src/test/end-to-end/pages/createCase/createCase.js
  src/test/end-to-end/pages/createCase/createCaseConfig.json
  src/test/end-to-end/pages/createCasePages/createCaseConfig.json
  src/test/end-to-end/pages/createCasePages/page1initiateCase1.js
  src/test/end-to-end/pages/createCasePages/page2claimantDetails.js
  src/test/end-to-end/pages/createCasePages/page3RespondentsDetails.js
  src/test/end-to-end/pages/createCasePages/page4claimantWorkAddressDetails.js
  src/test/end-to-end/pages/createCasePages/page5ClaimantOtherDetails.js
  src/test/end-to-end/pages/createCasePages/page6BroughtForwardDates.js
  src/test/end-to-end/pages/createCasePages/page7claimantRepresented.js
  src/test/end-to-end/pages/createCasePages/page8UploadDocumentsPage.js
  src/test/end-to-end/pages/createCasePages/page9SubmitPage.js
  src/test/end-to-end/pages/createReport/createReport.js
  src/test/end-to-end/pages/newCase/newCase.js
  src/test/end-to-end/pages/newCase/newCaseConfig.json
  src/test/end-to-end/pages/steps.js
  src/test/end-to-end/pages/uploadDocument/uploadDocument.js
  src/test/end-to-end/paths/manchester-Individual.js
  src/test/end-to-end/paths/scotland-Individual.js
  src/test/end-to-end/paths/validateHearingListedErrorMsgInWeekend.js
  src/test/end-to-end/paths/verifyBFActionOutstandingError.js
  src/test/end-to-end/paths/verifyLeedsCasePrintHearingLists.js
  src/test/end-to-end/paths/verifyManchesterCasePrintHearingLists.js
  src/test/end-to-end/paths/verifyRejectCase.js
  src/test/end-to-end/paths/verifyUploadDocument.js
Labels: ns:et, prd:et, rel:et-cos-pr-464

#460 RET-2185: Added default values for new env var
  src/main/resources/application-dev.properties
Labels: ns:et, prd:et, rel:et-cos-pr-460

#465 Ret 2185 5
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-465

#469 Update dependencies
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:et, prd:et, rel:et-cos-pr-469

#467 add step to generate OTP for 30 sec
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  package.json
  src/test/config.js
  src/test/end-to-end/helpers/etCaseHepler.js
  src/test/end-to-end/paths/verifyInitialConsideration.js
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-467

#471 Update dependencies
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  renovate.json
Labels: ns:et, prd:et, rel:et-cos-pr-471

#472 Add development versions of properties
  src/main/resources/application-cftlib.properties
  src/main/resources/application-dev.properties
Labels: ns:et, prd:et, rel:et-cos-pr-472

#470 RET-2411: ET3 Response Form doc generation
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/Et3ResponseData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/Et3ResponseDocument.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDataBuilder.java
  src/test/resources/et3ResponseDocument.json
Labels: ns:et, prd:et, rel:et-cos-pr-470

#474 fixed exception when creating et3 document and title is not provided
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-474

#475 Handle backslash in Cause List data
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TornadoDocumentFilter.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TornadoDocumentFilterTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/ResourceLoader.java
  src/test/resources/caseDataWithBackslash.json
Labels: ns:et, prd:et, rel:et-cos-pr-475

#478 Add docs for using docmosis in local dev environment
  README.md
  docs/docmosis.md
  src/main/resources/application-cftlib.properties
  src/main/resources/application-dev.properties
Labels: ns:et, prd:et, rel:et-cos-pr-478

#479 Updates for cftlib
  build.gradle
  docs/docmosis.md
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/DockerComposeProcessRunner.java
  src/main/resources/application-cftlib.properties
  src/main/resources/application-dev.properties
Labels: ns:et, prd:et, rel:et-cos-pr-479

#488 fix fortify failures
  Jenkinsfile_CNP
  src/test/config.js
  src/test/end-to-end/helpers/SauceLabsReportingHelper.js
  src/test/end-to-end/saucelabs.conf.js
Labels: ns:et, prd:et, rel:et-cos-pr-488

#489 R1.1 Merge Master
  Jenkinsfile_CNP
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/test/config.js
  src/test/end-to-end/helpers/SauceLabsReportingHelper.js
  src/test/end-to-end/saucelabs.conf.js
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-489

#490 Make docmosis cloud default option in dev
  src/main/resources/application-dev.properties
Labels: ns:et, prd:et, rel:et-cos-pr-490

#492 Add ITHC
  Jenkinsfile_CNP
Labels: ns:et, prd:et, rel:et-cos-pr-492

#496 added ccdId to template for referral notifications
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CCDRequestBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-496

#487 Refactored all the relevant tests that require the createCaseinCcd() …
  src/test/end-to-end/data/commonConfig.json
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/pages/amendCaseDetails/amendCaseDetails.js
  src/test/end-to-end/pages/amendCaseDetails/amendCaseDetailsWithCasePosition.js
  src/test/end-to-end/pages/amendClaimantDetails/amendClaimantDet.js
  src/test/end-to-end/pages/amendClaimantDetails/amendClaimantDetails.json
  src/test/end-to-end/pages/amendRespondentRepresentative/amendRespondentRepresentative.js
  src/test/end-to-end/pages/amendRespondentRepresentative/amendResponsdentRepresentative.json
  src/test/end-to-end/pages/steps.js
  src/test/end-to-end/paths/AcceptOrRejectCases.js
  src/test/end-to-end/paths/moveAcceptedCaseToCaseCloseStateErrorCheck.js
  src/test/end-to-end/paths/moveRejectCaseToCaseCloseStateErrorCheck.js
  src/test/end-to-end/paths/moveSubmittedCaseToCaseCloseErrorCheck.js
  src/test/end-to-end/paths/validateHearingListedErrorMsgInWeekend.js
  src/test/end-to-end/paths/verifyAcceptCase.js
  src/test/end-to-end/paths/verifyBFAction.js
  src/test/end-to-end/paths/verifyBFActionOutstandingError.js
  src/test/end-to-end/paths/verifyCaseClose.js
  src/test/end-to-end/paths/verifyCaseDetails.js
  src/test/end-to-end/paths/verifyClaimantDetails.js
  src/test/end-to-end/paths/verifyClaimantRepresentative.js
  src/test/end-to-end/paths/verifyCreateReport.js
  src/test/end-to-end/paths/verifyECMCase.js
  src/test/end-to-end/paths/verifyET1Serving.js
  src/test/end-to-end/paths/verifyFixCaseAPI.js
  src/test/end-to-end/paths/verifyFutureDateCheckOnTheHearingDetailsPage.js
  src/test/end-to-end/paths/verifyInitialConsideration.js
  src/test/end-to-end/paths/verifyJurisdiction.js
  src/test/end-to-end/paths/verifyLeedsCaseAllocateHearing.js
  src/test/end-to-end/paths/verifyLeedsCaseHearingDetails.js
  src/test/end-to-end/paths/verifyLeedsCaseJudgment.js
  src/test/end-to-end/paths/verifyLeedsCaseListHearing.js
  src/test/end-to-end/paths/verifyLeedsCasePrintHearingLists.js
  src/test/end-to-end/paths/verifyLeedsCaseTransfer.js
  src/test/end-to-end/paths/verifyLetters.js
  src/test/end-to-end/paths/verifyManchesterCaseAcceptCase.js
  src/test/end-to-end/paths/verifyManchesterCaseAllocateHearing.js
  src/test/end-to-end/paths/verifyManchesterCaseBFAction.js
  src/test/end-to-end/paths/verifyManchesterCaseClaimantDetails.js
  src/test/end-to-end/paths/verifyManchesterCaseClaimantRepresentative.js
  src/test/end-to-end/paths/verifyManchesterCaseClose.js
  src/test/end-to-end/paths/verifyManchesterCaseDetails.js
  src/test/end-to-end/paths/verifyManchesterCaseHearingDetails.js
  src/test/end-to-end/paths/verifyManchesterCaseJudgment.js
  src/test/end-to-end/paths/verifyManchesterCaseJurisdiction.js
  src/test/end-to-end/paths/verifyManchesterCaseLetters.js
  src/test/end-to-end/paths/verifyManchesterCaseListHearing.js
  src/test/end-to-end/paths/verifyManchesterCasePrintHearingLists.js
  src/test/end-to-end/paths/verifyManchesterCaseRejectCase.js
  src/test/end-to-end/paths/verifyManchesterCaseRespondentDetails.js
  src/test/end-to-end/paths/verifyManchesterCaseRespondentRepresentative.js
  src/test/end-to-end/paths/verifyManchesterCaseRestrictedReporting.js
  src/test/end-to-end/paths/verifyManchesterCaseTransfer.js
  src/test/end-to-end/paths/verifyManchesterFixCaseAPI.js
  src/test/end-to-end/paths/verifyRejectCase.js
  src/test/end-to-end/paths/verifyRespondentDetails.js
  src/test/end-to-end/paths/verifyRespondentRepresentative.js
  src/test/end-to-end/paths/verifyRestrictedReporting.js
  src/test/end-to-end/paths/verifyUploadDocument.js
Labels: ns:et, prd:et, rel:et-cos-pr-487

#498 Fix CVEs
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-498

#499 Fix readme links
  README.md
Labels: ns:et, prd:et, rel:et-cos-pr-499

#501 Enable et-sya-api to run within cftlib
  build.gradle
  docs/cftlib.md
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/CftlibConfig.java
Labels: ns:et, prd:et, rel:et-cos-pr-501

#494 PI27S4
  README.md
  build.gradle
  docs/cftlib.md
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/CftlibConfig.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/main/resources/application-dev.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CCDRequestBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-494

#504 Update build.gradle
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-504

#505 Update cftlib docs
  docs/cftlib.md
Labels: ns:et, prd:et, rel:et-cos-pr-505

#506 Re-enable fortify scans in nightly pipeline
  Jenkinsfile_nightly
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-506

#507 Sya api integration
  build.gradle
  src/cftlib/resources/compose/docker-compose.yml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-507
