Repository hmcts/et-ccd-callbacks, pull requests merged in 2022-01, with the labels that each got.

#60 Add subnet for postgres
  infrastructure/database.tf
Labels: ns:et, prd:et, rel:et-cos-pr-60

#66 Refactor Listing venue helper code
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingVenueHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingVenueHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/servingclaims/ServingClaimsReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-66

#65 Ret278 refactor venue addresses
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/config/VenueAddressesConfiguration.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/tribunaloffice/VenueAddress.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/VenueAddressReaderService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/VenueAddressesService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/exceptions/VenueAddressReaderException.java
  src/main/resources/venueAddressValues.xlsx
  src/main/resources/venueAddressValues.yml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/VenueAddressReaderServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/VenueAddressesServiceTest.java
  src/test/resources/venueAddressValues.xlsx
  src/test/resources/venueAddressValues.yml
Labels: ns:et, prd:et, rel:et-cos-pr-65

#68 Remove jcenter
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-68

#67 Populate dynamic venue lists for print hearing list event
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListingGenerationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PrintHearingListService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListingGenerationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PrintHearingListServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-67

#73 Update README
  README.md
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-73

#76 Remove CVEs
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-76
