Repository hmcts/et-ccd-callbacks, pull requests merged in 2022-07, with the labels that each got.

#329 Added callbacks for ET3 transfer application and hearing details
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3VettingHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3VettingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3VettingHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-329

#334 Ret 1849. Add post vetting event.
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingController.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-334

#335 Ret 2025
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationServiceTest.java
  src/test/resources/initialConsiderationCase1.json
  src/test/resources/initialConsiderationCase2.json
Labels: ns:et, prd:et, rel:et-cos-pr-335

#337 RET-1842: Fixed typo
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-337

#342 RET-2018: Add confirmation header message
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-342

#344 Update version of et-data-model to 1.0.31 and fix the broken tests.
  build.gradle
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkCreationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-344

#343 Ret 1845. Suggest hearing venue.
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDataBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-343

#338 RET-2019: Added aboutToSubmit endpoint for ET3 Vetting
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3VettingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3VettingService.java
  src/main/resources/application-dev.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3VettingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3VettingHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3VettingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-338

#346 Ret 2018
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
Labels: ns:et, prd:et, rel:et-cos-pr-346

#345 Ret 2102
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-345

#349 Initial Consideration : updated data model dependency
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-349

#350 ret-2087 fixed
  package.json
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-350

#355 RET-2025: Fixed issues with jurisdiction codes and incorrect responde…
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-355

#356 Add mid-event callback for validation of hearing preference options
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ClaimantHearingPreferencesController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ClaimantHearingPreferencesValidator.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ClaimantHearingPreferencesControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ClaimantHearingPreferencesValidatorTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-356

#357 Ret 2087 - fields were removed wrongly
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-357

#352 RET-2119 Fortify integration nightly pipeline
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-352

#358 Ret 2087
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingVenueHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingVenueHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-358

#362 Merge master
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:et, prd:et, rel:et-cos-pr-362

#360 RET-2028: Fixed cosmetic issues
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-360

#364 RET-2152: Fixed npe when existing jur code collection is null
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
Labels: ns:et, prd:et, rel:et-cos-pr-364

#365 Fixes and checkstyle
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/HearingDetailsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/filelocation/FileLocationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PersistentQHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ET1ServingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/filelocation/FileLocationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/CourtWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/JurisdictionCodeTrackConstants.java
  src/test/functional/java/uk/gov/hmcts/ethos/replacement/functional/util/FileUtil.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/BFHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/claimsbyhearingvenue/ClaimsByHearingVenueCcdReportDataSourceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingsbyhearingtype/HearingsByHearingTypeCcdReportDataSourceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/servingclaims/ServingClaimsReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysCcdReportDataSourceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkCreationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3VettingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/casetransfer/CaseTransferToEcmServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ClaimsByHearingVenueExcelReportCreationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelDocManagementServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationMidEventValidationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDataBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-365

#366 RET-2161: ET1 Serving - Show Send Documents and Send to Acas pages
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/referencedata/JurisdictionCode.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ET1ServingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-366

#368 check styles fixes
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/BulkActionsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/BulkHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DynamicListHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/LabelsHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MultipleUtil.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UpdateDataModelBuilderTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/CaseSourceLocalReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/casesawaitingjudgment/CasesAwaitingJudgmentReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/casescompleted/CaseCompletedReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingstojudgments/HearingsToJudgmentsReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeReportTests.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/timetofirsthearing/TimeToFirstHearingReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkCreationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkSearchServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseCreationForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentGenerationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReferenceServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SubMultipleServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/VenueAddressReaderServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/VerifyTokenServiceServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-368

#372 Fixed respondent name
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3VettingHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-372

#373 bump data model version
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-373

#375 Merge master
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3VettingHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-375

#374 Added ET3 Response form callbacks
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-374

#370 RET-2121
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-370

#378 RET-2191. Make build fail on any checkstyles warnings.
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/filelocation/FileLocationController.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/broughtforward/BroughtForwardInitialiserTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingstojudgments/HearingsToJudgmentsReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/AddSingleCaseToMultipleServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TribunalOfficeServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/VenueAddressesServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelDocManagementServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/SingleCasesReadingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-378

#383 Bump Java Helm chart to 4.0.1
  charts/et-cos/Chart.yaml
  charts/et-cos/values.preview.template.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-383

#384 dependencies
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-384

#388 Merge java helm chart update
  charts/et-cos/Chart.yaml
  charts/et-cos/values.preview.template.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-388

#391 dependencies
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-391

#392 ET-data-model and et-common update reverted in master
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-392

#382 Ret 2155
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/JudgeController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/JudgeService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/JudgeControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/JudgeServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-382

#393 Ret 1861 modifications due to checkstyle fixes in et data model
  build.gradle
  package.json
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/BulkActionsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/DocumentGenerationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListingGenerationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/MultipleDocGenerationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PersistentQueueActionsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/BulkHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/CallbackRespHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ECCHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/timetofirsthearing/TimeToFirstHearingReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkSearchService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkUpdateService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationService.java
  src/test/functional/java/uk/gov/hmcts/ethos/replacement/functional/util/ResponseUtil.java
  src/test/functional/resources/testData/caseDetailsScotTest1.json
  src/test/functional/resources/testData/caseDetailsScotTest2.json
  src/test/functional/resources/testData/caseDetailsScotTest3.json
  src/test/functional/resources/testData/caseDetailsScotTest4.json
  src/test/functional/resources/testData/defaults/postDefaultScotTest1.json
  src/test/functional/resources/testData/defaults/postDefaultScotTest2.json
  src/test/functional/resources/testData/defaults/postDefaultTest3.json
  src/test/functional/resources/testData/defaults/postDefaultTest4.json
  src/test/functional/resources/testData/defaults/preDefaultScotTest1.json
  src/test/functional/resources/testData/defaults/preDefaultScotTest2.json
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3VettingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/BulkHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkCreationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkSearchServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SubMultipleServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDataBuilder.java
  src/test/resources/reportDetailsTest4.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-393

#397 Bump netty-tcnative-2.0.54.Final
  build.gradle
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-397
