Repository hmcts/et-ccd-callbacks, pull requests merged in 2022-06, with the labels that each got.

#269 Release PI26-S2
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/filelocation/FileLocationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/CourtWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/courtworker/CourtWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/admin/AdminData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/CourtWorkerRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/FileLocationRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/filelocation/FileLocationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/filelocation/SaveFileLocationException.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/CourtWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/courtworker/CourtWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/filelocation/FileLocationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/CourtWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/courtworker/CourtWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/filelocation/FileLocationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/CourtWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/courtworker/CourtWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/AdminDataBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-269

#270 RET-1785
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/CourtWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/JudgeController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/judge/JudgeController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/admin/AdminData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/JudgeRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/JudgeService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/SaveJudgeException.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/judge/JudgeService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/JudgeControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/judge/JudgeControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/JudgeServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/judge/JudgeServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-270

#280 RET-1873
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/CourtWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/JudgeController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/CourtWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/JudgeService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/CourtWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/JudgeControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/CourtWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/JudgeServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-280

#289 Ret 1867
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/CourtWorkerRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/FileLocationRepository.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/filelocation/FileLocationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/CourtWorkerService.java
  src/test/integration/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/EtCosPostgresqlContainer.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/filelocation/FileLocationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/filelocation/FileLocationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/CourtWorkerServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-289

#282 Merge ECM R5.0.31
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListingGenerationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/letters/InvalidCharacterCheck.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/bulkaddsingles/BulkAddSinglesValidator.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/bulkaddsingles/SingleCasesValidator.java
  src/test/end-to-end/data/commonConfig.json
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/pages/common/constants.js
  src/test/end-to-end/pages/createReport/createReport.js
  src/test/end-to-end/pages/steps.js
  src/test/end-to-end/paths/verifyCreateReport.js
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/letters/InvalidCharacterCheckTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/bulkaddsingles/BulkAddSinglesValidatorTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/bulkaddsingles/SingleCasesValidatorTest.java
  src/test/resources/caseDetailsTest13.json
  src/test/resources/caseDetailsTest14.json
  src/test/resources/caseDetailsTest15.json
Labels: ns:et, prd:et, rel:et-cos-pr-282

#286 RET-829
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PersistentQHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PersistentQHelperService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/casetransfer/CaseTransferEventService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/casetransfer/CaseTransferToEcmParams.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/casetransfer/CaseTransferToEcmService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PersistentQHelperServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/casetransfer/CaseTransferEventServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/casetransfer/CaseTransferToEcmServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDataBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-286

#287 RET-1852: New endpoint for returning serving documents other type name
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/resources/exampleV4.json
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-287

#290 RET-1860
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/CreateController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/CreateService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/CreateControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/CreateServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-290

#294 Fix venue text in dynamic hearings
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DynamicListHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DynamicListHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDataBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-294

#292 Ret 1854
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ET1ServingService.java
  src/main/resources/exampleV4.json
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ET1ServingServiceTest.java
  src/test/resources/midServingCaseDetailsTest.json
Labels: ns:et, prd:et, rel:et-cos-pr-292

#297 RET-1838
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-297

#300 added address
  src/main/resources/venueAddressValues.yml
Labels: ns:et, prd:et, rel:et-cos-pr-300

#299 Fix Scotland venue for dynamic hearing list
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DynamicListHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DynamicListHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDataBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-299

#298 Ret 1965
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3VettingHelper.java
  src/main/resources/application-dev.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3VettingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3VettingHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDataBuilder.java
  src/test/resources/caseDetailsTest1.json
Labels: ns:et, prd:et, rel:et-cos-pr-298

#302 Merge master
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-302

#305 RET-2040
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/HearingDetailsController.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/HearingDetailsControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-305

#304 RET-1838
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/IntWrapper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-304

#309 RET-2067
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-309

#308 hearingDetails changes
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-308

#307 RET-1839
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
  src/test/resources/et1VettingTest1.json
  src/test/resources/et1VettingTest2.json
Labels: ns:et, prd:et, rel:et-cos-pr-307

#311 RET-1515
  charts/et-cos/values.preview.template.yaml
  charts/et-cos/values.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-311

#312 RET-2073
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/hearingdetails/HearingDetailsService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/hearingdetails/HearingDetailServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-312

#320 RET-2020
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3VettingController.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3VettingControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-320

#317 Merge ECM R5.0.32
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UpdateDataModelBuilder.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelDocManagementService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleBatchUpdate2Service.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleUploadService.java
  src/main/resources/application-dev.properties
  src/test/end-to-end/codecept.conf.js
  src/test/end-to-end/pages/IDAM/signIn.js
  src/test/end-to-end/pages/acceptanceCase/acceptCase.js
  src/test/end-to-end/pages/acceptanceCase/rejectCase.js
  src/test/end-to-end/pages/amendCaseDetails/amendCaseDetails.js
  src/test/end-to-end/pages/amendCaseDetails/amendCaseDetailsWithCasePosition.js
  src/test/end-to-end/pages/amendClaimantDetails/amendClaimantDetails.js
  src/test/end-to-end/pages/amendClaimantRepresentative/amendClaimantRepresentative.js
  src/test/end-to-end/pages/amendHearing/addAmendHearing.js
  src/test/end-to-end/pages/amendJudgment/addAmendJudgment.js
  src/test/end-to-end/pages/amendJurisdiction/addAmendJurisdiction.js
  src/test/end-to-end/pages/amendRespondentDetails/amendRespondentDetails.js
  src/test/end-to-end/pages/amendRespondentRepresentative/amendRespondentRepresentative.js
  src/test/end-to-end/pages/broughtForward/broughtForward.js
  src/test/end-to-end/pages/desposeCase/desposeCase.js
  src/test/end-to-end/pages/fixCaseApi/fixCaseApi.js
  src/test/end-to-end/pages/generateCorrespondence/generateCorrespondence.js
  src/test/end-to-end/pages/hearingDetails/updateHearingDetails.js
  src/test/end-to-end/pages/nextStep/nextStep.js
  src/test/end-to-end/pages/printHearingLists/printHearingLists.js
  src/test/end-to-end/pages/restrictedCases/restrictedCases.js
  src/test/end-to-end/pages/steps.js
  src/test/end-to-end/paths/moveAcceptedCaseToCaseCloseStateErrorCheck.js
  src/test/end-to-end/paths/moveRejectCaseToCaseCloseStateErrorCheck.js
  src/test/end-to-end/paths/moveSubmittedCaseToCaseCloseErrorCheck.js
  src/test/end-to-end/paths/verifyFutureDateCheckOnTheHearingDetailsPage.js
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UpdateDataModelBuilderTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleUploadServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-317

#316 RET-1840
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDataBuilder.java
  src/test/resources/et1VettingTest1.json
  src/test/resources/et1VettingTest2.json
Labels: ns:et, prd:et, rel:et-cos-pr-316

#322 RET-1985: Added ET3 Vetting Respondent Name and Address pages
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3VettingHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3VettingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3VettingHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDataBuilder.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/RespondentBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-322

#328 Fix CVE for release branch
  config/owasp/suppressions.xml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3VettingHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-328

#313 Ret 1842
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/referencedata/JurisdictionCode.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ConciliationTrackService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/JurisdictionCodeTrackConstants.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ET1ServingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-313

#327 Ret 2083
  src/test/functional/java/uk/gov/hmcts/ethos/replacement/functional/util/FileUtil.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/MockHttpURLConnection.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-327

#330 Revert "Ret 2018"
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3VettingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3VettingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3VettingHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDataBuilder.java
  src/test/resources/et1VettingTest1.json
  src/test/resources/et1VettingTest2.json
Labels: ns:et, prd:et, rel:et-cos-pr-330

#332 RET-2018: rebased branch from sprint 5
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-332
