Repository hmcts/et-ccd-callbacks, pull requests merged in 2023-12, with the labels that each got.

#1482 Update build.gradle - CVE
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-1482

#1386 Pet 1.2.3
  bin/docker-clean.sh
  bin/import-ccd-definition.sh
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/prehearingdeposit/PreHearingDepositController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/admin/AdminData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/prehearingdeposit/PreHearingDepositCallbackResponse.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/prehearingdeposit/PreHearingDepositData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/prehearingdeposit/PreHearingDepositRequest.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelReadingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/prehearingdeposit/PreHearingDepositService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/prehearingdeposit/PreHearingDepositControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/prehearingdeposit/PreHearingDepositServiceTest.java
  src/test/resources/PreHearingDepositData.xlsx
Labels: ns:et, prd:et, enable_keep_helm, rel:et-cos-pr-1386

#1486 Bump data model
  build.gradle
Labels: ns:et, prd:et, enable_keep_helm, rel:et-cos-pr-1486

#1505 RET-4607
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-1505
