Repository hmcts/et-ccd-callbacks, pull requests merged in 2023-10, with the labels that each got.

#1188 Update RolesConstants.java
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/RolesConstants.java
Labels: ns:et, prd:et, rel:et-cos-pr-1188

#1192 RET-4273
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentGenerationService.java
Labels: ns:et, prd:et, rel:et-cos-pr-1192

#1206 RET-2462: Update Region to RegionId
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1206

#1157 RET-4021: Display notification banner on Tribunal Response
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1157

#1153 Add category to ET3 doc
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1153

#1228 RET-4309
  src/main/resources/venueAddressValues.yml
Labels: ns:et, prd:et, rel:et-cos-pr-1228

#1254 Ret 3891 doc links in pdf br
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseAdmReplyHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/DocumentUtil.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseAdmReplyHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-1254

#1247 RET-4285: Added CaseFlags and CaseLinking code behind a feature flag
  build.gradle
  src/cftlib/resources/compose/mocks/wiremock/__files/prd/case-flags.json
  src/cftlib/resources/compose/mocks/wiremock/__files/prd/case-links.json
  src/cftlib/resources/compose/mocks/wiremock/__files/prd/organisation1_users_without_roles.json
  src/cftlib/resources/compose/mocks/wiremock/__files/prd/organisations_by_internal_api.json
  src/cftlib/resources/compose/mocks/wiremock/__files/prd/party-flags.json
  src/cftlib/resources/compose/mocks/wiremock/mappings/prd/case-flags.json
  src/cftlib/resources/compose/mocks/wiremock/mappings/prd/case-links.json
  src/cftlib/resources/compose/mocks/wiremock/mappings/prd/party-flags.json
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseLinksController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/CaseLinksHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseFlagsService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseLinksEmailService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleService.java
  src/main/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseLinksControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/CaseLinksHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NotificationHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseFlagsServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseLinksEmailServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleServiceTest.java
  src/test/utils/java/uk/gov/hmcts/ethos/utils/CaseDataBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-1247

#1277 Update caseNameHmctsInternal when amending Claimant or Respondent
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
Labels: ns:et, prd:et, rel:et-cos-pr-1277

#1289 Add feature flag to caseNameHmctsInternal
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
Labels: ns:et, prd:et, rel:et-cos-pr-1289

#1294 Update tagEnv for perftest
  infrastructure/main.tf
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-1294

#1295 Update build.gradle
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-1295

#1298 RET-4359 - Allow empty collection
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/RespondentTellSomethingElseHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-1298

#1309 Fix func test
  config/owasp/suppressions.xml
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/BaseFunctionalTest.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/BundlesRespondentControllerFunctionalTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1309

#1227 Add migration controller for case flags
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseFlagsDataMigrationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseFlagsService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseFlagsDataMigrationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseFlagsServiceTest.java
  src/test/resources/exampleV2.json
Labels: ns:et, prd:et, rel:et-cos-pr-1227

#1308 RET-4004 WA enablers
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyService.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/TseRespondentReplyControllerFunctionalTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1308

#1156 Pet 1.2.2
  bin/debugCFTLIB.sh
  bin/import-ccd-definition-zsh.sh
  bin/import-ccd-definition.sh
  bin/kill-residual-processes.sh
  bin/run-crossbrowser-tests.sh
  bin/startCFTLIB.sh
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdmReplyController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseRespondentReplyController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/TseAdminReplyData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/TseReplyData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Constants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseAdmReplyHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseAdminHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/DocumentUtil.java
  src/main/resources/venueAddressValues.yml
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/TseAdminControllerFunctionalTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdmReplyControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseAdmReplyHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseAdminHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyServiceTest.java
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-1156

#1336 Flexi DB
  charts/et-cos/Chart.yaml
  charts/et-cos/values.yaml
  infrastructure/database-flexi.tf
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-1336
