Repository hmcts/et-ccd-callbacks, pull requests merged in 2023-02, with the labels that each got.

#666 TSE: For adding api test to pipeline
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-666

#658 Ret 2843
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/NoticeOfChangeController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/SolicitorRole.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocRespondentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NoticeOfChangeAnswersConverter.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NoticeOfChangeFieldPopulator.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/dynamiclists/DynamicRespondentRepresentative.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/AdminUserService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CcdCaseAssignment.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocCcdService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentRepresentativeService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/NoticeOfChangeControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/SolicitorRoleTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocRespondentHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NoticeOfChangeAnswersConverterTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NoticeOfChangeFieldPopulatorTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/AdminUserServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocCcdServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentRepresentativeServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-658

#664 RET-2539
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdminController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/TseAdminControllerFunctionalTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdminControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-664

#621 Ret 2616
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseClaimantController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-621

#669 RET-3133 Upgrade to helm version 4.0.11
  charts/et-cos/Chart.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-669

#672 Moved ET1 Position logic to postDefaultValues controller instead of m…
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  package.json
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DefaultValuesReaderService.java
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-672

#674 Ret 3134 Terraform & Azurerm Upgrade
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-674

#667 Verify BFActions Automation
  src/test/end-to-end/data/et-ccd-basic-data.json
  src/test/end-to-end/pages/broughtForward/broughtForward.js
  src/test/end-to-end/pages/et1Vetting/helpers/listingDetails.js
  src/test/end-to-end/paths/verifyBFAction.js
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-667

#675 RET-2997
  build.gradle
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-675

#673 Ret 2617 - Apps & Case Mgmt common – Rule 92 question - both parties are system users (CitizenUI)
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
Labels: ns:et, prd:et, rel:et-cos-pr-673

#679 RET-3155
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-679

#680 Adding the right version of node to use for this repository...
  .nvmrc
Labels: ns:et, prd:et, rel:et-cos-pr-680

#682 Ret 3155 new
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelperTest.java
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-682

#684 Upload Documents Automation and Refactoring
  src/test/end-to-end/pages/uploadDocument/uploadDocument.js
  src/test/end-to-end/paths/verifyUploadDocument.js
Labels: ns:et, prd:et, rel:et-cos-pr-684

#685 Ret-3157 Upgrade to Yarn v3
  .gitignore
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  build.gradle
  package.json
  yarn.lock
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-685

#686 Claimant Representative Automation and Refactoring
  src/test/end-to-end/pages/amendClaimantRepresentative/amendClaimantRepresentative.js
  src/test/end-to-end/paths/verifyClaimantRepresentative.js
Labels: ns:et, prd:et, rel:et-cos-pr-686

#687 Upload Documents Automation
  src/test/end-to-end/pages/uploadDocument/uploadDocument.js
Labels: ns:et, prd:et, rel:et-cos-pr-687

#690 Ret-3157 Upgrade to yarn v3
  build.gradle
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-690

#691 RET-2290
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyService.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/RespondentTellSomethingElseControllerFunctionalTest.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/TseAdminControllerFunctionalTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-691

#692 Ret 3126
  src/main/resources/application.properties
  src/test/integration/resources/application.properties
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-692

#689 RET-2862
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-689

#693 Adding the tests for Claimant Details...
  src/test/end-to-end/pages/amendClaimantDetails/amendClaimantDet.js
  src/test/end-to-end/pages/amendClaimantDetails/amendClaimantDetails.json
  src/test/end-to-end/pages/amendClaimantDetails/helper/claimantContactDetails.js
  src/test/end-to-end/pages/amendClaimantDetails/helper/claimantDetails.js
  src/test/end-to-end/pages/amendClaimantDetails/helper/claimantHearingPreferences.js
  src/test/end-to-end/pages/amendClaimantDetails/helper/claimantIndividualDetails.js
  src/test/end-to-end/pages/amendClaimantDetails/helper/claimantOtherDetails.js
  src/test/end-to-end/pages/amendClaimantDetails/helper/claimantWorkDetails.js
  src/test/end-to-end/paths/verifyClaimantDetails.js
Labels: ns:et, prd:et, rel:et-cos-pr-693

#696 Temporarily disable ES query
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/CreateService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/CreateServiceTest.java
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-696

#688 Ret 2949
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/SendNotificationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/SendNotificationTypeData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/HearingSelectionService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/SendNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-688

#697 Revert admin query
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/CreateService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/CreateServiceTest.java
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-697

#699 Revert RET3126 and RET3155
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelper.java
  src/main/resources/application.properties
  src/test/integration/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-699

#700 PET-1.1.0.7_Upgrade Helm, Terraform, Azurerm, Yarn upgrade
  .gitignore
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  build.gradle
  charts/et-cos/Chart.yaml
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  package.json
  yarn.lock
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-700

#695 Case Transfer Automation and Refactoring
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/pages/caseTransfer/caseTransfer.js
  src/test/end-to-end/pages/caseTransfer/caseTransferECM.js
  src/test/end-to-end/pages/caseTransfer/caseTransferEngWales.js
  src/test/end-to-end/pages/caseTransfer/caseTransferScotland.js
  src/test/end-to-end/pages/common/constants.js
  src/test/end-to-end/pages/steps.js
  src/test/end-to-end/paths/verifyCaseTransfer.js
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-695

#703 RET-2949: Deleted additional letter question from send notification
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-703

#701 Extending the Verifiction by Checking the Respondent Representative T…
  src/test/end-to-end/pages/amendRespondentRepresentative/amendRespondentRepresentative.js
Labels: ns:et, prd:et, rel:et-cos-pr-701

#698 RET-2289: Bump et-common version to 1.0.11. Change the application(TSE)creation status from 'Open' to 'In progress'
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
Labels: ns:et, prd:et, rel:et-cos-pr-698

#705 refactor case details and update ccd data inserted
  src/test/end-to-end/data/et-ccd-basic-data.json
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/helpers/etCaseHepler.js
  src/test/end-to-end/pages/amendCaseDetails/amendCaseDetails.js
  src/test/end-to-end/pages/amendCaseDetails/helper/caseDetails.js
  src/test/end-to-end/paths/verifyCaseDetails.js
Labels: ns:et, prd:et, rel:et-cos-pr-705

#706 Adding all the List Hearing tests and the Brought Forward Verificatio…
  build.gradle
  src/test/end-to-end/data/commonConfig.json
  src/test/end-to-end/pages/amendHearing/listHearing.js
  src/test/end-to-end/pages/amendRespondentRepresentative/amendRespondentRepresentative.js
  src/test/end-to-end/pages/broughtForward/broughtForward.js
  src/test/end-to-end/pages/uploadDocument/uploadDocument.js
  src/test/end-to-end/paths/verifyCaseListHearing.js
Labels: ns:et, prd:et, rel:et-cos-pr-706

#709 Adding the Set of Files for the ET1 Serving and the ET3 Notifications…
  src/test/end-to-end/pages/et1Serving/processEt1Serving.js
  src/test/end-to-end/pages/et3Notification/processingEt3Notification.js
  src/test/end-to-end/pages/uploadDocument/uploadDocument.js
  src/test/end-to-end/paths/verifyET1Serving.js
  src/test/end-to-end/paths/verifyET3Notification.js
  src/test/end-to-end/paths/verifyLeedsCaseTransfer.js
  src/test/end-to-end/paths/verifyUploadDocument.js
Labels: ns:et, prd:et, rel:et-cos-pr-709

#707 Ret 2843 email
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/NoticeOfChangeController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocCcdService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-707

#702 RET-2539
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
Labels: ns:et, prd:et, rel:et-cos-pr-702

#708 RET-2289
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-708

#713 Testing and trialing the Upload Document Fix....
  src/test/end-to-end/pages/et1Serving/processEt1Serving.js
  src/test/end-to-end/pages/uploadDocument/uploadDocument.js
  src/test/end-to-end/paths/verifyUploadDocument.js
Labels: ns:et, prd:et, rel:et-cos-pr-713

#711 Ret 3155
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-711

#715 Ret 2952 - added submitted page to sendNotification
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/SendNotificationController.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/SendNotificationControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-715

#712 RET-3026 Select application to view
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseViewApplicationsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseViewApplicationsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-712

#714 Ret 3217
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-714

#720 CDAM file download option removed
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentManagementService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentManagementServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-720

#710 Create Reports Automation and Refactoring
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/pages/createReport/createReport.js
  src/test/end-to-end/paths/verifyCreateReport.js
Labels: ns:et, prd:et, rel:et-cos-pr-710

#716 RET-2879
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseRespondToTribunalController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/PseRespondToTribunalControllerFunctionalTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseRespondToTribunalControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-716

#721 Ret 3206
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CloseReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-721

#718 RET-2539
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-718

#717 Ret 3116
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/Et1VettingData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/InitialConsiderationData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et1VettingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/InitialConsiderationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-717

#722 Ret 3206
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CloseReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-722

#727 Ret 3117 fix
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/InitialConsiderationHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-727

#728 Ret 3220 3221
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataService.java
Labels: ns:et, prd:et, rel:et-cos-pr-728

#729 Ret 3218
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
Labels: ns:et, prd:et, rel:et-cos-pr-729

#726 RET-2851
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseRespondentReplyController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/TseRespondentReplyControllerFunctionalTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-726

#725 RET-3028
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseRespondToTribunalController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-725

#730 Ret 3155 welsh
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-730

#731 Ret 3116 3117 pdf dateformat
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et1VettingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/InitialConsiderationHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-731

#724 RET-2951: Send a notification (ECM) - notify selected parties
  charts/et-cos/values.preview.template.yaml
  charts/et-cos/values.yaml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/SendNotificationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/main/resources/application-cftlib.properties
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/integration/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-724

#734 Ret 3116, 3117 dateformat
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
Labels: ns:et, prd:et, rel:et-cos-pr-734

#733 RET-3026 Filtering applications by status fix
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-733

#735 Ret 3116 dateformat
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et1VettingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/InitialConsiderationHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-735

#736 RET-3006
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseRespondentViewController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondentViewService.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/PseRespondentViewControllerFunctionalTest.java
  src/test/apiTest/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseRespondentViewControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondentViewServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-736

#737 Ret 2953 added selectNotification
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondNotificationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondNotificationControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-737

#740 Ret 3241 3217
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/claimsbyhearingvenue/ClaimsByHearingVenueReport.java
Labels: ns:et, prd:et, rel:et-cos-pr-740

#742 Ret 3169
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-742

#741 RET-3048: View all Judgement, Orders and Notification
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseViewNotificationsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondentViewService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseViewNotificationsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondentViewServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-741

#744 ret-2274 implementation
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentGenerationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/UserService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentManagementServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-744

#743 RET-2962
  charts/et-cos/values.yaml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseRespondToTribunalController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalService.java
  src/main/resources/application-cftlib.properties
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/apiTest/resources/application.properties
  src/test/integration/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseRespondToTribunalControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-743

#745 RET-3244 - Set application status to open and state to in progress
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
Labels: ns:et, prd:et, rel:et-cos-pr-745

#747 Fix CVE
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-747
