Repository hmcts/et-ccd-callbacks, pull requests merged in 2023-05, with the labels that each got.

#915 Bump spring security version - CVE fix
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-915

#876 RET-3386: Update all R1.2 email templates to use dynamic links
  charts/et-cos/values.yaml
  config/pmd/rulesetTest.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/config/NotificationProperties.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/NotificationServiceConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyService.java
  src/main/resources/application-dev.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-876

#917 RET-3278: Fixed missing field data in Record a Decision
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/TableMarkupConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MarkdownHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MarkdownHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondentViewServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-917

#916 Ret-3555 - Set hearing date on email
  package.json
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelperTest.java
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-916

#918 1.1.2 - Merge fix
  build.gradle
  config/owasp/suppressions.xml
  renovate.json
Labels: ns:et, prd:et, rel:et-cos-pr-918

#906 Ret 3488
  build.gradle
  charts/et-cos/Chart.yaml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/HearingDetailsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/HearingSelectionService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/hearingdetails/HearingDetailsService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/hearingdetails/HearingDetailServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-906

#921 Build fix - Reduce PMD issues
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-921

#926 Bf report fixes
  build.gradle
  charts/et-cos/Chart.yaml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReportDoc.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/BfExcelReportService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelCreationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelReportDocumentInfoService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReportDocTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelReportDocumentInfoServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-926

#930 RET-3279: Added ccdId to two noc templates
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-930

#922 RET-3549: Aligning multiple file uploads for applications and notifications
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseViewApplicationsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/TseReplyData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MarkdownHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseViewApplicationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmCloseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseViewApplicationsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmCloseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-922

#860 PET-1.1.1.3
  .gitignore
  Dockerfile
  build.gradle
  charts/et-cos/Chart.yaml
  charts/et-cos/values.yaml
  lib/AI-Agent.xml
  lib/applicationinsights.json
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/dynamiclists/DynamicJudgements.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReportData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReportDoc.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/claimsbyhearingvenue/ClaimsByHearingVenueReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/BfExcelReportService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ClaimsByHearingVenueExcelReportCreationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ClaimsByHearingVenueExcelReportDocumentInfoService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelCreationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelReportDocumentInfoService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleLetterService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReportDocTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/BfExcelReportServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ClaimsByHearingVenueExcelReportCreationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ClaimsByHearingVenueExcelReportDocumentInfoServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelCreationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelReportDocumentInfoServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-860

#933 RET-3549: Falling back to display basic file link when metadata cannot be reached
  charts/et-cos/Chart.yaml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentManagementService.java
Labels: ns:et, prd:et, rel:et-cos-pr-933

#936 Fix et3Response.notification.tribunal.template.id not working locally.
  src/main/resources/application-dev.properties
Labels: ns:et, prd:et, rel:et-cos-pr-936

#934 Ret 3253 Apps & Case Management common-View an application/case judgment from Case overview page
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmCloseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmCloseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-934

#937 RET-3592: Removed several tabs for caseworker-employment and caseworker-employment-legalrep-solicitor
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/LegalRepDocumentsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/LegalRepDocumentsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/DocumentFixtures.java
Labels: ns:et, prd:et, rel:et-cos-pr-937

#938 Ret 3608. Fix Rep details on ET3 form
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-938

#940 RET-3608. Et3 address on no c
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/NoticeOfChangeController.java
Labels: ns:et, prd:et, rel:et-cos-pr-940

#928 Ret 3501
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-928

#941 url fix
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-941

#944 Remove unneeded document_management.caseWorkerRole property
  src/main/resources/application.properties
  src/test/contractTest/resources/application.properties
  src/test/end-to-end/pages/createReport/createReport.js
Labels: ns:et, prd:et, rel:et-cos-pr-944

#946 Functional test
  src/test/end-to-end/paths/verifyCreateReport.js
Labels: ns:et, prd:et, rel:et-cos-pr-946

#943 Ret 2924
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-943

#948 RET-3440. Fix old template ids
  charts/et-cos/values.yaml
  src/main/resources/application-dev.properties
Labels: ns:et, prd:et, rel:et-cos-pr-948

#945 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-cos-pr-945

#947 Ret 3669 Wrong title on View a Judgement, Order or Notification
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/TableMarkupConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MarkdownHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondentViewServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-947

#951 Fix Respondent Id bug
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocRespondentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NoticeOfChangeFieldPopulator.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocRespondentHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-951

#952 Ret 3719. Fix functional tests
  Jenkinsfile_nightly
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/LegalRepDocumentsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/NoticeOfChangeController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocRespondentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NoticeOfChangeFieldPopulator.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeService.java
  src/test/end-to-end/pages/amendCaseDetails/helper/caseDetails.js
  src/test/end-to-end/paths/verifyCreateReport.js
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/LegalRepDocumentsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocRespondentHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/DocumentFixtures.java
Labels: ns:et, prd:et, rel:et-cos-pr-952

#953 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-cos-pr-953

#954 Claimant names by type
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-954

#955 cve fix
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-955

#950 RET-3610
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-950

#957 Company name indentation corrected
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-957
