Repository hmcts/et-ccd-callbacks, pull requests merged in 2023-04, with the labels that each got.

#783 Pet 1.1.1.2 ET-PET PI29 Sprint 3
  bin/docker-clean.sh
  bin/download-idam.sh
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListingGenerationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DefaultValuesReaderService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/HearingSelectionService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/AllocateHearingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/ScotlandAllocateHearingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/hearingdetails/HearingDetailsService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/JurisdictionCodeTrackConstants.java
  src/test/end-to-end/helpers/etCaseHepler.js
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListingGenerationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DefaultValuesReaderServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/HearingSelectionServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/AllocateHearingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/ScotlandAllocatedHearingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/hearingdetails/HearingDetailServiceTest.java
  src/test/resources/caseDetailsScotTest5.json
  src/test/resources/caseDetailsTest21.json
  src/test/resources/exampleV1.json
Labels: ns:et, prd:et, rel:et-cos-pr-783

#856 Pet 1.1.1.3
  bin/docker-clean.sh
  bin/download-idam.sh
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListingGenerationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DefaultValuesReaderService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/HearingSelectionService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/AllocateHearingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/ScotlandAllocateHearingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/hearingdetails/HearingDetailsService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/JurisdictionCodeTrackConstants.java
  src/test/end-to-end/helpers/etCaseHepler.js
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListingGenerationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DefaultValuesReaderServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/HearingSelectionServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/AllocateHearingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/ScotlandAllocatedHearingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/hearingdetails/HearingDetailServiceTest.java
  src/test/resources/caseDetailsScotTest5.json
  src/test/resources/caseDetailsTest21.json
  src/test/resources/exampleV1.json
Labels: ns:et, prd:et, rel:et-cos-pr-856

#854 RET-3344: Added ET3 response related documents into documentCollection
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/DocumentFixtures.java
Labels: ns:et, prd:et, rel:et-cos-pr-854

#857 change mem limit
  Dockerfile
  charts/et-cos/Chart.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-857

#829 RET-3323
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReportData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/claimsbyhearingvenue/ClaimsByHearingVenueReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/BfExcelReportService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ClaimsByHearingVenueExcelReportCreationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ClaimsByHearingVenueExcelReportDocumentInfoService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelCreationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelReportDocumentInfoService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleLetterService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ClaimsByHearingVenueExcelReportCreationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ClaimsByHearingVenueExcelReportDocumentInfoServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelReportDocumentInfoServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-829

#861 Fix getSelectedListing
  charts/et-cos/Chart.yaml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/HearingSelectionService.java
  src/test/end-to-end/data/et-ccd-basic-data.json
  src/test/end-to-end/pages/amendCaseDetails/helper/caseDetails.js
  src/test/end-to-end/pages/amendRespondentRepresentative/amendRespondentRepresentative.js
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-861

#853 RET-3370
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdminController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmCloseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdminControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmCloseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-853

#855 Ret 3366
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-855

#863 log messages added
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
Labels: ns:et, prd:et, rel:et-cos-pr-863

#837 Remove suppressions
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-837

#869 RET-3365 and 3410
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-869

#870 RET-3323 - wrap text
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/BfExcelReportService.java
Labels: ns:et, prd:et, rel:et-cos-pr-870

#871 Ret 3323 minor fix - cell range
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/BfExcelReportService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ClaimsByHearingVenueExcelReportCreationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelCreationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/BfExcelReportServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ClaimsByHearingVenueExcelReportCreationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelCreationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-871

#872 RET-3458
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
Labels: ns:et, prd:et, rel:et-cos-pr-872

#874 Fix CheckStyle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseService.java
Labels: ns:et, prd:et, rel:et-cos-pr-874

#873 RET-3098
  .gitignore
  Dockerfile
  build.gradle
  charts/et-cos/Chart.yaml
  charts/et-cos/values.yaml
  lib/AI-Agent.xml
  lib/applicationinsights.json
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/dynamiclists/DynamicJudgements.java
Labels: ns:et, prd:et, rel:et-cos-pr-873

#878 Ret 3098
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-878

#879 Ret 3098
  lib/applicationinsights.json
Labels: ns:et, prd:et, rel:et-cos-pr-879

#880 Cleaned template IDs
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
Labels: ns:et, prd:et, rel:et-cos-pr-880

#877 RET-3400
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/TableMarkupConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmCloseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmCloseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-877

#798 Gradle changes to run Integration tests config as per SSCS API
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-798

#883 RET-3485 Respond to a Notification fails when claimant email address is missing
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-883

#867 RET-3072
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/BundlesRespondentController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BundlesRespondentService.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/BundlesRespondentControllerFunctionalTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/BundlesRespondentControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BundlesRespondentServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-867

#881 RET-3106: Added page 3 of Bundles Respondent journey
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/BundlesRespondentController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BundlesRespondentService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/BundlesRespondentControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BundlesRespondentServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-881

#888 appinsights version update
  Dockerfile
Labels: ns:et, prd:et, rel:et-cos-pr-888

#886 Enabler for RET-3146 & RET-3433; Interface to rd-professional
  build.gradle
  charts/et-cos/values.yaml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/rdprofessional/OrganisationClient.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeService.java
  src/main/resources/application-cftlib.properties
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/integration/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-886

#890 Ret 3433. Populate representative details in ET3 form
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelperTest.java
  src/test/resources/et3ResponseDocument.json
Labels: ns:et, prd:et, rel:et-cos-pr-890

#891 Remove outdated api-test property
  src/test/apiTest/resources/application.properties
Labels: ns:et, prd:et, rel:et-cos-pr-891

#892 organisationclient-debug: Temp logging
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeService.java
Labels: ns:et, prd:et, rel:et-cos-pr-892

#893 Integration tests report
  Jenkinsfile_CNP
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-893

#882 RET-3438: Fix for NOC email is not being sent to Removed Organisation
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/NoticeOfChangeController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocCcdService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeService.java
  src/main/resources/application-dev.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/NoticeOfChangeControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocCcdServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDataBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-882

#896 Fixed sonar bug
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-896

#897 Ret 3320 - Filter claimant applications
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseViewApplicationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseViewApplicationHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-897

#899 RET-3433: Added missing s2s token
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/rdprofessional/OrganisationClient.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-899

#904 Fix functional test to reflect rejection validation
  src/test/end-to-end/data/commonConfig.json
Labels: ns:et, prd:et, rel:et-cos-pr-904

#901 Ret 3146: Remove Debug Code
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeService.java
Labels: ns:et, prd:et, rel:et-cos-pr-901

#900 RET-3108: Added validate upload mid callback
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/BundlesRespondentController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BundlesRespondentService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/BundlesRespondentControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BundlesRespondentServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-900

#907 Ret 3438
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/rdprofessional/OrganisationClient.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-907

#909 RET-0000: Fix for ET3 Response Form when respondent rep address is null
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-909

#905 RET-3496 - Add respondent upload to the document collection
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-905

#910 Update Chart.yaml
  charts/et-cos/Chart.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-910

#911 Fix imports
  build.gradle
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-911
