Repository hmcts/et-ccd-callbacks, pull requests merged in 2023-03, with the labels that each got.

#755 RET-Cve-fix
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-755

#756 Fix Master
  build.gradle
  charts/et-cos/Chart.yaml
  config/owasp/suppressions.xml
  src/test/end-to-end/pages/createCase/caseHearingPref.js
Labels: ns:et, prd:et, rel:et-cos-pr-756

#760 CVE Fix
  config/owasp/suppressions.xml
  src/test/end-to-end/pages/amendClaimantDetails/helper/claimantDetails.js
  src/test/end-to-end/pages/amendClaimantDetails/helper/claimantHearingPreferences.js
Labels: ns:et, prd:et, rel:et-cos-pr-760

#751 RET-3270
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseAdminHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-751

#754 RET-3252
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
Labels: ns:et, prd:et, rel:et-cos-pr-754

#759 RET-3259
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/TseApplicationBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-759

#746 RET-2969
  charts/et-cos/values.yaml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseRespondToTribunalController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalService.java
  src/main/resources/application-cftlib.properties
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/apiTest/resources/application.properties
  src/test/integration/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseRespondToTribunalControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-746

#762 Ret 2985
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
Labels: ns:et, prd:et, rel:et-cos-pr-762

#763 RET-2786 - Added not started yet status to respondent application
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
Labels: ns:et, prd:et, rel:et-cos-pr-763

#766 Added null check for organisation to remove
  config/owasp/suppressions.xml
  package.json
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/NoticeOfChangeController.java
  src/test/end-to-end/pages/amendClaimantDetails/helper/claimantDetails.js
  src/test/end-to-end/pages/amendClaimantDetails/helper/claimantHearingPreferences.js
  src/test/end-to-end/paths/verifyCreateReport.js
Labels: ns:et, prd:et, rel:et-cos-pr-766

#670 PET-1.1.0.7
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/Et1VettingData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/InitialConsiderationData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et1VettingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/InitialConsiderationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/claimsbyhearingvenue/ClaimsByHearingVenueCcdReportDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/claimsbyhearingvenue/ClaimsByHearingVenueESQuery.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/claimsbyhearingvenue/ClaimsByHearingVenueReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/claimsbyhearingvenue/ClaimsByHearingVenueReportDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentGenerationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentManagementService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/UserService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/CreateService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/bfaction/BfActionReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/claimsbyhearingvenue/ClaimsByHearingVenueCcdReportDataSourceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/claimsbyhearingvenue/ClaimsByHearingVenueReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentManagementServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReportDataServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-670, add-or-update

#772 Functional test fix
  src/test/end-to-end/pages/amendClaimantDetails/amendClaimantDet.js
  src/test/end-to-end/pages/amendClaimantDetails/amendClaimantDetails.json
Labels: ns:et, prd:et, rel:et-cos-pr-772

#752 New branch of ret-3172 implementation
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/resources/exampleV1.json
Labels: ns:et, prd:et, rel:et-cos-pr-752

#770 RET-2964
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseRespondToTribunalController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalService.java
  src/main/resources/application-cftlib.properties
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/apiTest/resources/application.properties
  src/test/integration/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseRespondToTribunalControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-770

#774 RET-3314: Add Close Application Submit
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdminController.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/TseAdminControllerFunctionalTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdminControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-774

#777 Addition of 2 new shell scripts, docker-clean.sh & download-idam.sh
  bin/docker-clean.sh
  bin/download-idam.sh
Labels: ns:et, prd:et, rel:et-cos-pr-777

#778 RET-2962
  charts/et-cos/values.yaml
  src/main/resources/application.properties
Labels: ns:et, prd:et, rel:et-cos-pr-778

#753 RET-3257: Renamed Give details to Details of the Application
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-753

#781 Ret-3341 Staff cause list not displaying Claimant's title
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-781

#779 RET-2896 View application and responses
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseViewApplicationsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseViewApplicationHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseViewApplicationsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseViewApplicationHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-779

#784 Adding missing tests to the class CaseManagementForCaseWorkerService
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/resources/caseDetailsScotTest5.json
  src/test/resources/caseDetailsTest21.json
Labels: ns:et, prd:et, rel:et-cos-pr-784

#782 Ret 2954 Provide something Tribunal asked for - Respond to a notification (ECM)
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondNotificationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-782

#786 RET-2954 fix bug in document markdown
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-786

#787 RET-2964
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalService.java
Labels: ns:et, prd:et, rel:et-cos-pr-787

#788 RET-3310
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
Labels: ns:et, prd:et, rel:et-cos-pr-788

#790 RET-3275: Renamed Give details to Details of the application
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-790

#793 Ret 3337,3342
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/CreateController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDataBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-793

#797 RET-3305
  charts/et-cos/values.yaml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseService.java
  src/main/resources/application-cftlib.properties
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/apiTest/resources/application.properties
  src/test/integration/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-797

#800 RET-3325
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-800

#801 RET-3267
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-801

#803 RET-3276
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-803

#805 sonar test coverage
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-805

#807 Ret 3371
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/TseApplicationBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-807

#813 Ret 3319 new
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
Labels: ns:et, prd:et, rel:et-cos-pr-813

#817 CVE-2022-1471
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-817

#809 RET-2927
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-809

#818 RET-3401
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-818

#820 Ret 3392
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/NoticeOfChangeController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/exceptions/CcdInputOutputException.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/CaseConverter.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocRespondentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocCcdService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocRespondentHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocCcdServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-820

#819 Ret 3409
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-819

#826 Adding all of the relevant Fixes for the Snake Yaml...
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-826

#824 RET-3400
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-824

#830 Changed test
  src/test/end-to-end/pages/amendClaimantDetails/amendClaimantDet.js
  src/test/end-to-end/pages/amendClaimantDetails/amendClaimantDetails.json
Labels: ns:et, prd:et, rel:et-cos-pr-830

#799 Ret 2982
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/HearingSelectionService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/AllocateHearingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/ScotlandAllocateHearingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/hearingdetails/HearingDetailsService.java
  src/test/end-to-end/helpers/etCaseHepler.js
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/HearingSelectionServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/AllocateHearingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/ScotlandAllocatedHearingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/hearingdetails/HearingDetailServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-799

#822 Ret 3992 2
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/NotificationServiceConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/TableMarkupConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3VettingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseViewApplicationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/EmailServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-822

#802 Ret 2956 Provide something Tribunal asked for - Respond to a notification (ECM) - notify selected parties (email)
  build.gradle
  charts/et-cos/values.yaml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondNotificationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/main/resources/application-cftlib.properties
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/integration/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-802

#834 RET-3407: Added condition to show pay frequency only when earning det…
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-834

#833 et-data-model tag number update
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-833

#839 update tomcat to version 9.0.73
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-839

#843 update org.springframework.boot to v2.7.10
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-843

#845 cve suppress
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-845

#840 RET-2949
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-840

#842 Ret 2957
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondNotificationController.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/RespondNotificationControllerFunctionalTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/SendNotificationControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-842

#850 Fix Nightly build
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-850

#848 RET-3390
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
Labels: ns:et, prd:et, rel:et-cos-pr-848

#849 Ret 3295
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-849

#835 RET-3335
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/TableMarkupConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseRespondToTribunalController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseRespondentViewController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondentViewService.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/PseRespondentViewControllerFunctionalTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseRespondentViewControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondentViewServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-835

#847 Ret 3024 case judgement
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/helpers/etCaseHepler.js
  src/test/end-to-end/pages/amendJudgment/addAmendJudgment.js
  src/test/end-to-end/pages/judgment/hearingJudgement.js
  src/test/end-to-end/pages/judgment/judgment.js
  src/test/end-to-end/pages/steps.js
  src/test/end-to-end/paths/verifyBFAction.js
  src/test/end-to-end/paths/verifyCaseAllocateHearing.js
  src/test/end-to-end/paths/verifyCaseJudgment.js
  src/test/end-to-end/paths/verifyCaseListHearing.js
  src/test/end-to-end/paths/verifyClaimantDetails.js
  src/test/end-to-end/paths/verifyFixCaseAPI.js
  src/test/end-to-end/paths/verifyJurisdiction.js
  src/test/end-to-end/paths/verifyLeedsCaseJudgment.js
  src/test/end-to-end/paths/verifyLeedsCasePrintHearingLists.js
  src/test/end-to-end/paths/verifyLetters.js
  src/test/end-to-end/paths/verifyRejectCase.js
  src/test/end-to-end/paths/verifyRespondentDetails.js
  src/test/end-to-end/paths/verifyRespondentRepresentative.js
Labels: ns:et, prd:et, rel:et-cos-pr-847
