Repository hmcts/et-ccd-callbacks, pull requests merged in 2023-09, with the labels that each got.

#1133 Ret 4130
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseRespondentReplyController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1133

#1135 update logic to set respondent id
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocRespondentHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-1135

#1137 RET-4163-fix for CVE-2023-41080
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-1137

#1134 RET-3514 Allow Non System Users Respond to an Application
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseRespondentReplyController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseRespondentReplyControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1134

#1140 Adding PMD reports to pipeline artifacts
  Jenkinsfile_CNP
Labels: ns:et, prd:et, rel:et-cos-pr-1140

#1138 RET-4019 Hearing unavailability dates
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/HearingUnavailabilityController.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/HearingUnavailabilityControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/HearingUnavailabilityControllerTest.java
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-1138

#1142 Check if email null or empty
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseLinksEmailService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseLinksEmailServiceTest.java
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-1142

#1146 NPE
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
Labels: ns:et, prd:et, rel:et-cos-pr-1146

#1148 RET-3514 Allow Non System Users Respond to an Application
  bin/import-ccd-definition-zsh.sh
  bin/utils/idam-user-token.sh
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-1148

#1144 Ret 4169
  build.gradle
  charts/et-cos/Chart.yaml
  charts/et-cos/values.preview.template.yaml
  charts/et-cos/values.yaml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/AcasCertificateController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/AcasService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DefaultValuesReaderService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
  src/main/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/AcasCertificateControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/AcasServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DefaultValuesReaderServiceTest.java
  src/test/resources/acasCertificate.json
Labels: ns:et, prd:et, rel:et-cos-pr-1144

#1150 Changed secret location
  charts/et-cos/Chart.yaml
  charts/et-cos/values.preview.template.yaml
  charts/et-cos/values.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-1150

#1152 ret-3891 implementation added
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdmReplyController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdminController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseRespondentReplyController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/TseAdminDecisionRecordData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/TseAdminReplyData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/TseReplyData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Constants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseAdminHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyService.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/TseAdminControllerFunctionalTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseAdminHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyServiceTest.java
Labels: ns:et, prd:et, enable_keep_helm, rel:et-cos-pr-1152

#1155 RET-4122 populate caseManagementLocationCode
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/config/TribunalOfficesConfiguration.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/tribunaloffice/CourtLocations.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementLocationCodeService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TribunalOfficesService.java
  src/main/resources/defaults.yml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementLocationCodeServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TribunalOfficeEpimmServiceTest.java
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-1155

#1159 RET-3891 Rollback for Recording a Decision
  bin/debugCFTLIB.sh
  bin/import-ccd-definition-zsh.sh
  bin/import-ccd-definition.sh
  bin/kill-residual-processes.sh
  bin/run-crossbrowser-tests.sh
  bin/startCFTLIB.sh
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdminController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/TseAdminDecisionRecordData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseAdmReplyHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseAdminHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/DocumentUtil.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseAdmReplyHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseAdminHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1159

#1128 Add callbacks for global search (RET-2462)
  build.gradle
  charts/et-cos/Chart.yaml
  charts/et-cos/values.preview.template.yaml
  charts/et-cos/values.yaml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/DocmosisApplication.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/config/TribunalOfficesConfiguration.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/GlobalSearchDataMigrationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/tribunaloffice/CourtLocations.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TribunalOfficesService.java
  src/main/resources/application.yaml
  src/main/resources/defaults.yml
  src/test/apiTest/resources/application.yaml
  src/test/contractTest/resources/application.yaml
  src/test/functional/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/GlobalSearchDataMigrationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TribunalOfficeServiceTest.java
  src/test/resources/caseDetailsScotTest1.json
Labels: ns:et, prd:et, enable_keep_helm, rel:et-cos-pr-1128

#1164 Add GS_profile role
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/RolesConstants.java
Labels: ns:et, prd:et, rel:et-cos-pr-1164

#1163 Pdf attachment to notification email
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdmReplyController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdmReplyControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1163

#1165 Temp Fix Test in Rule-92 branch
  build.gradle
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1165

#1166 Fix tests after data model bump
  build.gradle
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1166

#1160 RET-4152 and RET-4166
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
Labels: ns:et, prd:et, rel:et-cos-pr-1160

#1168 Add null pointer check for migration on case data fields
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
Labels: ns:et, prd:et, rel:et-cos-pr-1168

#1158 RET-4062
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseAdminHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseAdminHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1158

#1179 Remove search criteria update in global search migration
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/GlobalSearchDataMigrationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/GlobalSearchDataMigrationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1179

#1172 RET-3914 Generate PDF Document For Admin Decision
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdminController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/TseDecisionData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/TseDecisionDocument.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/DateUtil.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/TseAdminControllerFunctionalTest.java
  src/test/contractTest/java/uk/gov/hmcts/ethos/replacement/contract/idam/IdamApiConsumerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdminControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
Labels: ns:et, prd:et, enable_keep_helm, rel:et-cos-pr-1172
