Repository hmcts/et-ccd-callbacks, pull requests merged in 2023-07, with the labels that each got.

#1016 RET-3800: Add missing ExUI url to Tribunal template
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1016

#1018 For testing image build
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-1018

#1019 Revert "Ret 2924 (#943)"
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1019

#1015 RET-3690 - Update handling of responses and requests
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdmReplyController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1015

#1021 Update java chart version
  charts/et-cos/Chart.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-1021

#1020 Ret 3816 and RET-3868
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/dynamiclists/DynamicJudgements.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1020

#1026 Update Chart.yaml
  charts/et-cos/Chart.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-1026

#1000 Getting test to run with right tags and enabling all nightly test
  Jenkinsfile_CNP
  README.md
  build.gradle
  package.json
  src/test/config.js
  src/test/end-to-end/data/commonConfig.json
  src/test/end-to-end/helpers/etCaseHepler.js
  src/test/end-to-end/pages/IDAM/signIn.js
  src/test/end-to-end/pages/allocateHearing/allocateHearing.js
  src/test/end-to-end/pages/allocateHearing/helpers/selectAllocateHearingRoom.js
  src/test/end-to-end/pages/allocateHearing/helpers/selectListedHearing.js
  src/test/end-to-end/pages/allocateHearing/helpers/selectPersonelResources.js
  src/test/end-to-end/pages/allocateHearing/helpers/verifyHearingsAllocated.js
  src/test/end-to-end/pages/amendCaseDetails/amendCaseDetails.js
  src/test/end-to-end/pages/amendCaseDetails/amendCaseDetailsWithCasePosition.js
  src/test/end-to-end/pages/amendClaimantDetails/helper/claimantHearingPreferences.js
  src/test/end-to-end/pages/amendClaimantRepresentative/amendClaimantRepresentative.js
  src/test/end-to-end/pages/amendHearing/hearingListedInWeekend.js
  src/test/end-to-end/pages/amendHearing/listHearing.js
  src/test/end-to-end/pages/amendJurisdiction/addAmendJurisdiction.js
  src/test/end-to-end/pages/amendJurisdiction/addDisposalDate.js
  src/test/end-to-end/pages/amendRespondentDetails/amendRespondentDetails.js
  src/test/end-to-end/pages/amendRespondentRepresentative/amendRespondentRepresentative.js
  src/test/end-to-end/pages/broughtForward/bfActionsOutstandingError.js
  src/test/end-to-end/pages/broughtForward/broughtForward.js
  src/test/end-to-end/pages/caseTransfer/caseTransferECM.js
  src/test/end-to-end/pages/createCase/caseHearingPref.js
  src/test/end-to-end/pages/createReport/createReport.js
  src/test/end-to-end/pages/et1Serving/processEt1Serving.js
  src/test/end-to-end/pages/generateCorrespondence/generateCorrespondence.js
  src/test/end-to-end/pages/hearingDetails/hearingDetails.js
  src/test/end-to-end/pages/judgment/judgment.js
  src/test/end-to-end/pages/nextStep/nextStep.js
  src/test/end-to-end/pages/restrictedCases/restrictedCases.js
  src/test/end-to-end/pages/uploadDocument/uploadDocument.js
  src/test/end-to-end/paths/moveRejectCaseToCaseCloseStateErrorCheck.js
  src/test/end-to-end/paths/verifyCaseAllocateHearing.js
  src/test/end-to-end/paths/verifyCaseClose.js
  src/test/end-to-end/paths/verifyCaseListHearing.js
  src/test/end-to-end/paths/verifyCreateReport.js
  src/test/end-to-end/paths/verifyLetters.js
  src/test/end-to-end/paths/verifyUploadDocument.js
  src/test/end-to-end/paths/verifyValidationForDisposalDateJurisdiction.js
  src/test/end-to-end/saucelabs.conf.js
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-1000

#1029 add api users to nightly jenkins
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-cos-pr-1029

#1012 RET-3767: Added autoListFlag caseAdditionalSecurityFlag caseRestrictedFlag and caseInterpreterRequiredFlag
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseFlagsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseFlagsService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseFlagsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseFlagsServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1012

#1030 Ret 3890. submit TSE application documents
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/RespondentTellSomethingElseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/RespondentTellSomethingElseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1030

#1034 ECM-1311
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/dynamiclists/DynamicJudgements.java
Labels: ns:et, prd:et, rel:et-cos-pr-1034

#1038 RET-3731/RET-3719. Stop functional tests on prs
  package.json
Labels: ns:et, prd:et, rel:et-cos-pr-1038

#1039 RET-3810 - deep link url to Document tab
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1039

#1042 RET-3883
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/resources/caseDetailsTest4.json
Labels: ns:et, prd:et, rel:et-cos-pr-1042

#1049 Update data-model
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-1049

#1044 RET-3773: Determine private hearing flag
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdminController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseFlagsService.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/BaseFunctionalTest.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/BundlesRespondentControllerFunctionalTest.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/CaseActionsForCaseWorkerControllerFunctionalTest.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/InitialConsiderationControllerFunctionalTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdminControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseFlagsServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1044

#1040 RET-3397. Implement dynamic links for all templates
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EmailService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3NotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseService.java
  src/main/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/TestEmailService.java
Labels: ns:et, prd:et, rel:et-cos-pr-1040

#1041 RET-3675. Properties to yaml and remove unneeded ones
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/VerifyTokenService.java
  src/main/resources/application-cftlib.properties
  src/main/resources/application-dev.properties
  src/main/resources/application-dev.yaml
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/test/apiTest/resources/application.properties
  src/test/contractTest/resources/application.properties
  src/test/functional/resources/application.properties
  src/test/integration/resources/application.properties
Labels: ns:et, prd:et, rel:et-cos-pr-1041

#1070 Update cves
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-1070

#1033 Ret 3670. Reformat application details to be in one aligned table.
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MarkdownHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentManagementService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MarkdownHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondentViewServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmCloseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1033

#1066 RET-4044 - Bump data model
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1066
