Repository hmcts/et-ccd-callbacks, pull requests merged in 2023-06, with the labels that each got.

#959 RET-3713
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
Labels: ns:et, prd:et, rel:et-cos-pr-959

#961 Fix sonar issues
  config/pmd/ruleset.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-961

#958 Merge et3
  build.gradle
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/CftlibConfig.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/BulkHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/LabelsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MultiplesHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReplyToReferralHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDataBuilder.java
  src/test/resources/et3ResponseDocument.json
Labels: ns:et, prd:et, rel:et-cos-pr-958

#964 Added feature flag for et-hearings-api to application.properties
  src/main/resources/application.properties
Labels: ns:et, prd:et, rel:et-cos-pr-964

#966 RET-3688: Removed unused notStartedYet notification status
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-966

#967 Update application state when admin records a decision
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-967

#969 Disable functional ("end-to-end") tests, run @pr tests only.
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-969

#962 RET-3596: Rule 92 Screen displayed when other party is not a system user
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseRespondToTribunalController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseRespondentReplyController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseRespondToTribunalControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseRespondentReplyControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-962

#965 RET-2919
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-965

#923 Pet 1.1.1.4
  build.gradle
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/CftlibConfig.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/HearingDetailsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/BulkHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/LabelsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MultiplesHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReplyToReferralHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/HearingSelectionService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/hearingdetails/HearingDetailsService.java
  src/test/end-to-end/pages/amendCaseDetails/helper/caseDetails.js
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/hearingdetails/HearingDetailServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDataBuilder.java
  src/test/resources/et3ResponseDocument.json
Labels: ns:et, prd:et, rel:et-cos-pr-923

#956 RET-3461 - cleaned up method & removed confusing Ternarys
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/timetofirsthearing/TimeToFirstHearingReport.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/timetofirsthearing/TimeToFirstHearingReportTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-956

#968 RET-3763
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3NotificationController.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3NotificationControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-968

#972 UI tests fix
  build.gradle
  src/test/end-to-end/data/commonConfig.json
  src/test/end-to-end/pages/acceptanceCase/acceptCase.js
  src/test/end-to-end/pages/acceptanceCase/rejectCase.js
  src/test/end-to-end/pages/allocateHearing/allocateHearing.js
  src/test/end-to-end/pages/amendCaseDetails/amendCaseDetails.js
  src/test/end-to-end/pages/amendCaseDetails/amendCaseDetailsWithCasePosition.js
  src/test/end-to-end/pages/amendClaimantDetails/amendClaimantDet.js
  src/test/end-to-end/pages/amendClaimantRepresentative/amendClaimantRepresentative.js
  src/test/end-to-end/pages/amendHearing/listHearing.js
  src/test/end-to-end/pages/amendJurisdiction/addAmendJurisdiction.js
  src/test/end-to-end/pages/amendJurisdiction/addDisposalDate.js
  src/test/end-to-end/pages/amendRespondentDetails/amendRespondentDetails.js
  src/test/end-to-end/pages/amendRespondentRepresentative/amendRespondentRepresentative.js
  src/test/end-to-end/pages/broughtForward/bfActionsOutstandingError.js
  src/test/end-to-end/pages/broughtForward/broughtForward.js
  src/test/end-to-end/pages/caseTransfer/caseTransferECM.js
  src/test/end-to-end/pages/createReport/createReport.js
  src/test/end-to-end/pages/et1Serving/processEt1Serving.js
  src/test/end-to-end/pages/et1Vetting/helpers/beforeYouStartVetting.js
  src/test/end-to-end/pages/et3Notification/processingEt3Notification.js
  src/test/end-to-end/pages/fixCaseApi/fixCaseApi.js
  src/test/end-to-end/pages/generateCorrespondence/generateCorrespondence.js
  src/test/end-to-end/pages/hearingDetails/hearingDetails.js
  src/test/end-to-end/pages/judgment/hearingJudgement.js
  src/test/end-to-end/pages/judgment/judgment.js
  src/test/end-to-end/pages/printHearingLists/printHearingLists.js
  src/test/end-to-end/pages/restrictedCases/restrictedCases.js
  src/test/end-to-end/pages/uploadDocument/uploadDocument.js
  src/test/end-to-end/paths/verifyCreateCase.js
Labels: ns:et, prd:et, rel:et-cos-pr-972

#976 RET-2515: Added HMCTSServiceId to newly created cases
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/main/resources/application.properties
  src/test/apiTest/resources/application.properties
  src/test/contractTest/resources/application.properties
  src/test/functional/resources/application.properties
  src/test/integration/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/resources/application.properties
Labels: ns:et, prd:et, rel:et-cos-pr-976

#981 cve
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-981

#983 RET-3808
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentGenerationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentGenerationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-983

#984 RET-3794: Allows LR to respond to request/order from Tribunal
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseRespondentReplyController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseRespondentReplyControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-984

#985 fix quality gate issues
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseCreationForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCasesSendingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleUploadServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-985

#979 RET-3702
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-979

#986 RET-3784
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
Labels: ns:et, prd:et, rel:et-cos-pr-986

#988 Suggestions for code quality
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
Labels: ns:et, prd:et, rel:et-cos-pr-988

#989 RET-3664: Create/Manage Case Flags
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseFlagsService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseFlagsServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-989

#993 RET-0000: Reintroduced HMC objects
  build.gradle
  src/test/resources/caseDetailsTest4.json
Labels: ns:et, prd:et, rel:et-cos-pr-993

#975 Ret 3684. Status update for respondents applications. #382
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdmReplyController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseRespondentReplyController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseViewApplicationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmCloseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseRespondentReplyControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseViewApplicationHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleUploadServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/DocumentTypeItemUtil.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/TseApplicationUtil.java
  src/test/utils/java/uk/gov/hmcts/ethos/utils/TseApplicationBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-975

#991 RET-3805
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/StaffImportStrategy.java
Labels: ns:et, prd:et, rel:et-cos-pr-991

#995 RET-3794: Added mid event input validation for TSE Respondent respond
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseRespondentReplyController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-995

#1001 RET-3801 & RET-3800: Send emails to Claimant and Tribunal when LR res…
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/NotificationServiceConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyService.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/integration/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1001

#971 PET-1.1.2.2
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3NotificationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentGenerationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/StaffImportStrategy.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3NotificationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentGenerationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-971

#1005 RET-3765: Created changes to setInternalHmctsName
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1005

#1013 RET-3799: Send Ack email when LR responds to Tribunal
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyService.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/integration/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1013
