Repository hmcts/et-ccd-callbacks, pull requests merged in 2023-01, with the labels that each got.

#601 RET-2994 added exclustions to suppressions file
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-601

#602 CVEs
  build.gradle
  config/owasp/suppressions.xml
  package.json
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SingleReferenceServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-602

#605 Ret 3009
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferController.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDataBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-605

#608 RET-2981
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelperTest.java
  src/test/resources/caseDetailsTest1.json
Labels: ns:et, prd:et, rel:et-cos-pr-608

#609 document collection corrected for referral reply
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
Labels: ns:et, prd:et, rel:et-cos-pr-609

#610 additional correction
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
Labels: ns:et, prd:et, rel:et-cos-pr-610

#611 RET-3009
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/casetransfer/CaseTransferOfficeService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDataBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-611

#613 update yarn lock
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-613

#614 Ret 2963: Removed the names and salutations from the NOC emails
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-614

#615 RET-2983 implementation
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-615

#616 Ret 2983
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-616

#606 PET - PI28S6
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/casetransfer/CaseTransferOfficeService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDataBuilder.java
  src/test/resources/caseDetailsTest1.json
Labels: ns:et, prd:et, rel:et-cos-pr-606

#612 Testing the new PR for the hearing events...
  src/test/end-to-end/data/commonConfig.json
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/pages/allocateHearing/allocateHearing.js
  src/test/end-to-end/pages/amendHearing/listHearing.js
  src/test/end-to-end/pages/amendJurisdiction/addAmendJurisdiction.js
  src/test/end-to-end/pages/amendJurisdiction/addDisposalDate.js
  src/test/end-to-end/pages/hearingDetails/hearingDetails.js
  src/test/end-to-end/pages/steps.js
  src/test/end-to-end/paths/verifyCreateCase.js
  src/test/end-to-end/paths/verifyRespondentRepresentative.js
  src/test/end-to-end/paths/verifyValidationForDisposalDateJurisdiction.js
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-612

#620 Removed all the Manchester Tests as part of Refactoring the ET CCD Ca…
  src/test/end-to-end/paths/verifyManchesterCaseAcceptCase.js
  src/test/end-to-end/paths/verifyManchesterCaseAllocateHearing.js
  src/test/end-to-end/paths/verifyManchesterCaseBFAction.js
  src/test/end-to-end/paths/verifyManchesterCaseClaimantDetails.js
  src/test/end-to-end/paths/verifyManchesterCaseClaimantRepresentative.js
  src/test/end-to-end/paths/verifyManchesterCaseClose.js
  src/test/end-to-end/paths/verifyManchesterCaseDetails.js
  src/test/end-to-end/paths/verifyManchesterCaseHearingDetails.js
  src/test/end-to-end/paths/verifyManchesterCaseJudgment.js
  src/test/end-to-end/paths/verifyManchesterCaseJurisdiction.js
  src/test/end-to-end/paths/verifyManchesterCaseLetters.js
  src/test/end-to-end/paths/verifyManchesterCaseListHearing.js
  src/test/end-to-end/paths/verifyManchesterCasePrintHearingLists.js
  src/test/end-to-end/paths/verifyManchesterCaseRejectCase.js
  src/test/end-to-end/paths/verifyManchesterCaseRespondentDetails.js
  src/test/end-to-end/paths/verifyManchesterCaseRespondentRepresentative.js
  src/test/end-to-end/paths/verifyManchesterCaseRestrictedReporting.js
  src/test/end-to-end/paths/verifyManchesterCaseTransfer.js
  src/test/end-to-end/paths/verifyManchesterFixCaseAPI.js
Labels: ns:et, prd:et, rel:et-cos-pr-620

#625 RET-3019: Added missing manage-user scope needed to get user by id fr…
  src/main/resources/application.properties
Labels: ns:et, prd:et, rel:et-cos-pr-625

#622 Added all of the initially retagged tests for main and nightly execut…
  build.gradle
  src/test/end-to-end/paths/moveRejectCaseToCaseCloseStateErrorCheck.js
  src/test/end-to-end/paths/moveSubmittedCaseToCaseCloseErrorCheck.js
  src/test/end-to-end/paths/validateHearingListedErrorMsgInWeekend.js
  src/test/end-to-end/paths/verifyBFActionOutstandingError.js
  src/test/end-to-end/paths/verifyCaseClose.js
  src/test/end-to-end/paths/verifyCaseDetails.js
  src/test/end-to-end/paths/verifyClaimantRepresentative.js
  src/test/end-to-end/paths/verifyCreateReport.js
  src/test/end-to-end/paths/verifyECMCase.js
  src/test/end-to-end/paths/verifyET1Serving.js
  src/test/end-to-end/paths/verifyET1Vetting.js
  src/test/end-to-end/paths/verifyET3Notification.js
  src/test/end-to-end/paths/verifyET3processing.js
  src/test/end-to-end/paths/verifyET3response.js
  src/test/end-to-end/paths/verifyFixCaseAPI.js
  src/test/end-to-end/paths/verifyFutureDateCheckOnTheHearingDetailsPage.js
  src/test/end-to-end/paths/verifyInitialConsideration.js
  src/test/end-to-end/paths/verifyJurisdiction.js
  src/test/end-to-end/paths/verifyLeedsCaseAllocateHearing.js
  src/test/end-to-end/paths/verifyLeedsCaseHearingDetails.js
  src/test/end-to-end/paths/verifyLeedsCaseJudgment.js
  src/test/end-to-end/paths/verifyLeedsCaseListHearing.js
  src/test/end-to-end/paths/verifyLeedsCasePrintHearingLists.js
  src/test/end-to-end/paths/verifyLeedsCaseTransfer.js
  src/test/end-to-end/paths/verifyLetters.js
  src/test/end-to-end/paths/verifyReferrrals.js
  src/test/end-to-end/paths/verifyRejectCase.js
  src/test/end-to-end/paths/verifyRespondentDetails.js
  src/test/end-to-end/paths/verifyRespondentRepresentative.js
  src/test/end-to-end/paths/verifyRestrictedReporting.js
  src/test/end-to-end/paths/verifyUploadDocument.js
  src/test/end-to-end/paths/verifyValidationForDisposalDateJurisdiction.js
Labels: ns:et, prd:et, rel:et-cos-pr-622

#626 Testing the refactoring done for the processCaseToAccepted State
  src/test/end-to-end/helpers/etCaseHepler.js
Labels: ns:et, prd:et, rel:et-cos-pr-626

#624 Ret 2995
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DefaultValuesReaderService.java
Labels: ns:et, prd:et, rel:et-cos-pr-624

#623 RET-3029
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-623

#628 RET-2892
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
Labels: ns:et, prd:et, rel:et-cos-pr-628

#627 Adding all of the Changes that is required for a Reject A Case...
  src/test/end-to-end/codecept.conf.js
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/helpers/etCaseHepler.js
  src/test/end-to-end/pages/acceptanceCase/rejectCase.js
  src/test/end-to-end/pages/amendCaseDetails/amendCaseDetailsWithCasePosition.js
  src/test/end-to-end/pages/initialConsideration/initialConsiderationStartPage.js
  src/test/end-to-end/paths/moveAcceptedCaseToCaseCloseStateErrorCheck.js
  src/test/end-to-end/paths/moveRejectCaseToCaseCloseStateErrorCheck.js
  src/test/end-to-end/paths/moveSubmittedCaseToCaseCloseErrorCheck.js
  src/test/end-to-end/paths/verifyECMCase.js
  src/test/end-to-end/paths/verifyRejectCase.js
Labels: ns:et, prd:et, rel:et-cos-pr-627

#631 Adding the Fixes for Reject a Case and the associated moveRejectCaseT…
  package.json
  src/test/end-to-end/helpers/etCaseHepler.js
  src/test/end-to-end/paths/moveRejectCaseToCaseCloseStateErrorCheck.js
  src/test/end-to-end/paths/moveSubmittedCaseToCaseCloseErrorCheck.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-631

#633 Ret 3029
  package.json
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-633

#636 Verified BF Action Outstanding Errors
  src/test/end-to-end/pages/broughtForward/bfActionsOutstandingError.js
  src/test/end-to-end/paths/verifyBFActionOutstandingError.js
Labels: ns:et, prd:et, rel:et-cos-pr-636

#639 Ret 3029
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-639

#638 Fixed the validateHearingListedErrorMsgInWeekend
  src/test/end-to-end/data/commonConfig.json
  src/test/end-to-end/pages/amendHearing/hearingListedInWeekend.js
  src/test/end-to-end/paths/validateHearingListedErrorMsgInWeekend.js
Labels: ns:et, prd:et, rel:et-cos-pr-638

#644 Verified Letters Automation
  src/test/end-to-end/pages/generateCorrespondence/generateCorrespondence.js
  src/test/end-to-end/paths/verifyLetters.js
Labels: ns:et, prd:et, rel:et-cos-pr-644

#646 Ret 3076
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
Labels: ns:et, prd:et, rel:et-cos-pr-646

#650 RET-3078 implementation
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/dynamiclists/DynamicRespondentRepresentative.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-650

#648 Updated text for automation security
  src/test/end-to-end/pages/generateCorrespondence/generateCorrespondence.js
Labels: ns:et, prd:et, rel:et-cos-pr-648

#653 Refactor hearing date time stamp
  src/test/end-to-end/helpers/utils.js
  src/test/end-to-end/pages/hearingDetails/hearingDetails.js
  src/test/end-to-end/paths/verifyValidationForDisposalDateJurisdiction.js
Labels: ns:et, prd:et, rel:et-cos-pr-653

#654 RET-2876
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-654

#649 Ret 3024 verify et1 vetting
  package.json
  src/test/end-to-end/codecept.conf.js
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/pages/et1Vetting/caseDetails1ET1Vetting.js
  src/test/end-to-end/pages/et1Vetting/caseDetails2ET1Vetting.js
  src/test/end-to-end/pages/et1Vetting/caseDetails3ET1Vetting.js
  src/test/end-to-end/pages/et1Vetting/caseDetails4ET1Vetting.js
  src/test/end-to-end/pages/et1Vetting/checkYourAnswersET1Vetting.js
  src/test/end-to-end/pages/et1Vetting/et1CaseVettingOptions1.js
  src/test/end-to-end/pages/et1Vetting/et1VettingBeforeYouStart.js
  src/test/end-to-end/pages/et1Vetting/et1VettingJourney.js
  src/test/end-to-end/pages/et1Vetting/finalNotesET1Vetting.js
  src/test/end-to-end/pages/et1Vetting/furtherQET1Vetting.js
  src/test/end-to-end/pages/et1Vetting/helpers/additionalInformation.js
  src/test/end-to-end/pages/et1Vetting/helpers/beforeYouStartVetting.js
  src/test/end-to-end/pages/et1Vetting/helpers/canWeServeTheClaim.js
  src/test/end-to-end/pages/et1Vetting/helpers/checkYourAnswers.js
  src/test/end-to-end/pages/et1Vetting/helpers/furtherDetails.js
  src/test/end-to-end/pages/et1Vetting/helpers/includeAnyOtherFactors.js
  src/test/end-to-end/pages/et1Vetting/helpers/isThereAnACASCertificate.js
  src/test/end-to-end/pages/et1Vetting/helpers/jurisdictionCodes.js
  src/test/end-to-end/pages/et1Vetting/helpers/listingDetails.js
  src/test/end-to-end/pages/et1Vetting/helpers/possibleSubstantiveDefects.js
  src/test/end-to-end/pages/et1Vetting/helpers/referalToJudgeOrLegalOfficer.js
  src/test/end-to-end/pages/et1Vetting/helpers/referalToRegionalEmploymentJudgeOrVicePresident.js
  src/test/end-to-end/pages/et1Vetting/helpers/trackAllocation.js
  src/test/end-to-end/pages/et1Vetting/helpers/tribunalLocation.js
  src/test/end-to-end/pages/et1Vetting/minReqInfo2ET1Vetting.js
  src/test/end-to-end/pages/et1Vetting/minReqInfoET1Vetting.js
  src/test/end-to-end/pages/et1Vetting/otherFactorsET1Vetting.js
  src/test/end-to-end/pages/et1Vetting/possibleReferal1ET1Vetting.js
  src/test/end-to-end/pages/et1Vetting/possibleReferal2ET1Vetting.js
  src/test/end-to-end/pages/steps.js
  src/test/end-to-end/paths/verifyET1Vetting.js
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-649

#655 RET-3019: Bugfix- Resolve unknown parameters in NOC emails
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-655

#656 Jenkins fix
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-656

#661 Working Respondent Representative Changes....
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/pages/amendRespondentRepresentative/amendRespondentRepresentative.js
  src/test/end-to-end/paths/verifyRespondentRepresentative.js
Labels: ns:et, prd:et, rel:et-cos-pr-661

#647 Verify Respondent Details Automation
  src/test/end-to-end/pages/amendRespondentDetails/amendRespondentDetails.js
  src/test/end-to-end/paths/verifyRespondentDetails.js
Labels: ns:et, prd:et, rel:et-cos-pr-647
