Repository hmcts/et-ccd-callbacks, pull requests merged in 2023-08, with the labels that each got.

#1065 Updated FT variables and Readme
  Jenkinsfile_CNP
  README.md
  charts/et-cos/Chart.yaml
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/BaseFunctionalTest.java
  src/test/apiTest/resources/application.properties
Labels: ns:et, prd:et, rel:et-cos-pr-1065

#1035 RET-3675. RET-3397. Fix application properties
  build.gradle
  charts/et-cos/Chart.yaml
  charts/et-cos/values.yaml
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/config/NotificationProperties.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/UploadDocumentController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EmailService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3NotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReferralService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/VerifyTokenService.java
  src/main/resources/application-cftlib.properties
  src/main/resources/application-dev.properties
  src/main/resources/application-dev.yaml
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/test/apiTest/resources/application.properties
  src/test/contractTest/resources/application.properties
  src/test/functional/resources/application.properties
  src/test/integration/resources/application.properties
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/UploadDocumentControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/EmailServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EmailServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReferralServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/TestEmailService.java
Labels: ns:et, prd:et, rel:et-cos-pr-1035

#1072 Fix Azurite/DM-store issue
  src/cftlib/resources/compose/docker-compose.yml
Labels: ns:et, prd:et, rel:et-cos-pr-1072

#1068 RET-3787- Email on update referral
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/UpdateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/UpdateReferralControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1068

#1076 Update CftlibConfig.java
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/CftlibConfig.java
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/RolesConstants.java
Labels: ns:et, prd:et, rel:et-cos-pr-1076

#1080 Update main.tf
  infrastructure/main.tf
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-1080

#1075 Upgrade: java-logging 6.0.1
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-1075

#1081 RET-4060 Update IDAM port to 5062
  bin/utils/idam-user-token.sh
  build.gradle
  src/cftlib/resources/compose/docker-compose.yml
  src/main/resources/application-cftlib.properties
Labels: ns:et, prd:et, rel:et-cos-pr-1081

#1085 Ret-4013 Solicitor permission updates
  bin/import-ccd-definition-zsh.sh
  bin/startCFTLIB.sh
  build.gradle
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/CftlibConfig.java
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/RolesConstants.java
  src/cftlib/resources/compose/docker-compose.yml
  src/cftlib/resources/compose/mocks/wiremock/mappings/prd/organisation1_users_without_roles.json
  src/cftlib/resources/compose/mocks/wiremock/mappings/prd/organisations_by_internal_api.json
Labels: ns:et, prd:et, rel:et-cos-pr-1085

#1084 Ret 3899 new
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdmReplyController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdminController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminService.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/TseAdmReplyControllerFunctionalTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdmReplyControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdminControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1084

#1098 date formate fix
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/RespondentTellSomethingElseHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/RespondentTellSomethingElseHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1098

#1102 additional changes added
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/TseReplyData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1102

#1100 RET-3514 Remove check for claimant system user
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseController.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1100

#1107 Revert "RET-3514 Remove check for claimant system user"
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseController.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1107

#1091 RET-3820 + RET-4081 - Send case linking emails
  build.gradle
  src/cftlib/resources/compose/mocks/wiremock/__files/prd/case-links.json
  src/cftlib/resources/compose/mocks/wiremock/mappings/prd/case-links.json
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseLinksController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/CaseLinksHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseLinksEmailService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/main/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseLinksControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/CaseLinksHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NotificationHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseLinksEmailServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/utils/java/uk/gov/hmcts/ethos/utils/CaseDataBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-1091

#1105 RET-4110
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/letters/InvalidCharacterCheck.java
Labels: ns:et, prd:et, rel:et-cos-pr-1105

#1111 RET-3514 Removed the control for claimants who are not system users.
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseController.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1111

#1115 null checks added
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-1115

#1116 Rule-92
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseController.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1116

#1112 RET 3842 hearing is linked flag
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseLinksController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseLinksControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1112

#1121 RET-4143 Vulnerability CVE-2022-44729 update
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-1121

#1122 respondent application missing field values fix
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/RespondentTellSomethingElseHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/RespondentTellSomethingElseHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1122

#1120 RET-3606 - Send mail to legal rep
  infrastructure/.terraform-version
  infrastructure/state.tf
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseLinksEmailService.java
  src/main/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseLinksEmailServiceTest.java
Labels: ns:et, prd:et, add-or-update, rel:et-cos-pr-1120

#1119 RET-4114
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1119

#1124 Fix for updated reformLogging
  build.gradle
  src/test/resources/logback-test.xml
Labels: ns:et, prd:et, rel:et-cos-pr-1124

#1125 perftest make application fix
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseController.java
Labels: ns:et, prd:et, rel:et-cos-pr-1125

#1126 RET-4113
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentGenerationService.java
Labels: ns:et, prd:et, rel:et-cos-pr-1126

#1088 RET-3462 - Tackle the CognitiveComplexity and CyclomaticComplexity
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentsReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationMidEventValidationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1088

#1129 RET-4119
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelperTest.java
  src/test/resources/expectedDocumentContentScot4.json
Labels: ns:et, prd:et, rel:et-cos-pr-1129
