Repository hmcts/et-ccd-callbacks, pull requests merged in 2024-02, with the labels that each got.

#1487 RET-4556-Update case flags when claimant or respondent details are updated
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
Labels: ns:et, prd:et, rel:et-cos-pr-1487

#1580 RET-4701: Added service for looking up cases
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseLookupService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseLookupServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1580

#1587 Update build.gradle
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-1587

#1588 RET-0000: downgrade cftlib to 1030 to avoid issues on WSL
  build.gradle
  renovate.json
Labels: ns:et, prd:et, rel:et-cos-pr-1588

#1589 New case flag fields in data model
  build.gradle
Labels: ns:et, prd:et, enable_keep_helm, no-changes, rel:et-cos-pr-1589

#1541 RET-4526
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/HearingSelectionService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/hearingdetails/HearingDetailsService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/HearingSelectionServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/AllocateHearingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/hearingdetails/HearingDetailServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1541

#1597 Fix CFV mapping field
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-1597

#1600 Update Dockerfile
  Dockerfile
Labels: ns:et, prd:et, rel:et-cos-pr-1600

#1605 RET-3991: Update PDFs for new IC
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/InitialConsiderationData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/InitialConsiderationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1605

#1620 ET-Cos - 20/02/2024
  infrastructure/database-flexi.tf
Labels: ns:et, prd:et, destroy, rel:et-cos-pr-1620

#1621 Change to V15
  charts/et-cos/Chart.yaml
  charts/et-cos/values.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-1621

#1086 Ret 3917
  build.gradle
  charts/et-cos/Chart.yaml
  charts/et-cos/values.yaml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/client/BundleApiClient.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CloseReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/DigitalCaseFileController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DigitalCaseFileHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/LabelsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DigitalCaseFileService.java
  src/main/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/DigitalCaseFileControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DigitalCaseFileHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DigitalCaseFileServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/ResourceLoader.java
  src/test/resources/stitchBundleRequest.json
Labels: ns:et, prd:et, rel:et-cos-pr-1086, no-changes

#1530 RET-4623
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentGenerationService.java
Labels: ns:et, prd:et, rel:et-cos-pr-1530

#1627 RET-4718: caseManagementLocation on caseTransfer
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementLocationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseLookupServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementLocationCodeServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementLocationServiceTest.java
  src/test/utils/java/uk/gov/hmcts/ethos/utils/ResourceUtils.java
Labels: ns:et, prd:et, rel:et-cos-pr-1627

#1569 RET-4712, RET-4697
  bin/pull-cftlib-images.sh
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelperTest.java
Labels: ns:et, prd:et, enable_keep_helm, no-changes, rel:et-cos-pr-1569

#1638 RET-4794
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
Labels: ns:et, prd:et, destroy, rel:et-cos-pr-1638

#1658 RET-3161: Hide Hearing from Notification when not present
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondentViewServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1658

#1653 RET-4687 - Set leadCaseId on multiple
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleHelperService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleHelperServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1653

#1661 Fix pipeline
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-1661

#1582 RET-4085
  build.gradle
Labels: ns:et, prd:et, enable_keep_helm, rel:et-cos-pr-1582

#1634 RET-4739
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationServiceTest.java
  src/test/resources/caseDetailsTest23.json
Labels: ns:et, prd:et, no-changes, rel:et-cos-pr-1634
