Repository hmcts/et-ccd-callbacks, pull requests merged in 2024-01, with the labels that each got.

#1517 RET-4585 - Reduce the number of PMD issues
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/BulkHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportDocHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingstojudgments/HearingsToJudgmentsReportData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReportDoc.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeReportData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/sessiondays/SessionDaysReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkSearchService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/casetransfer/CaseTransferUtils.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleScheduleService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/SubMultipleUpdateService.java
  src/test/resources/PreHearingDepositData.xlsx
Labels: ns:et, prd:et, rel:et-cos-pr-1517

#1523 RET-4623
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentGenerationService.java
Labels: ns:et, prd:et, rel:et-cos-pr-1523

#1524 Adding WA to CFTLib
  bin/init-db.sh
  build.gradle
  docs/cftlib.md
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/CftlibConfig.java
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/DockerComposeProcessRunner.java
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/RolesConstants.java
  src/cftlib/resources/compose/docker-compose.yml
  src/cftlib/resources/compose/mocks/wiremock/__files/prd/court-venues.json
  src/cftlib/resources/compose/mocks/wiremock/__files/prd/region-location.json
  src/cftlib/resources/compose/mocks/wiremock/mappings/prd/court-venues.json
  src/cftlib/resources/compose/mocks/wiremock/mappings/prd/region-location.json
  src/cftlib/resources/compose/wa-docker-compose.yml
Labels: ns:et, prd:et, rel:et-cos-pr-1524

#1522 Work Allocation - Preview 292
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-1522

#1526 RET-3296: Rule21Referral cronjob
  Jenkinsfile_CNP
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/DocmosisApplication.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/wa/BFActionsScheduledTasks.java
  src/main/resources/application.yaml
  src/test/apiTest/resources/application.yaml
  src/test/functional/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/wa/BFActionsScheduledTasksTest.java
  src/test/resources/bfActionTask_oneExpiredDate.json
Labels: ns:et, prd:et, rel:et-cos-pr-1526

#1532 RET-0000: Added new users for better local testing
  build.gradle
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/CftlibConfig.java
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/RolesConstants.java
Labels: ns:et, prd:et, rel:et-cos-pr-1532

#1047 RET-3898
  bin/docker-clean.sh
  bin/kill-residual-processes.sh
  bin/pull-cftlib-images.sh
  bin/startCFTLIB.sh
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseClaimantController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseRespondentReplyController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/UploadDocumentController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et1VettingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/InitialConsiderationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/LabelsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/timetofirsthearing/TimeToFirstHearingReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3VettingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/TseRespondentReplyControllerFunctionalTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/UploadDocumentControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyServiceTest.java
  src/test/utils/java/uk/gov/hmcts/ethos/utils/CaseDataBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-1047, enable_keep_helm

#1534 RET-4679: Fixed hearing date in the past breaking bundles
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BundlesRespondentService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BundlesRespondentServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1534

#1528 RET-4528
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1528

#1535 RET-4689
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/DocumentGenerationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelperTest.java
  src/test/resources/exampleV2.json
Labels: ns:et, prd:et, rel:et-cos-pr-1535

#1539 Fix file extension
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
Labels: ns:et, prd:et, rel:et-cos-pr-1539

#1550 RET-4677: Populate hmctsCaseCategory for ExUI
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1550
