Repository hmcts/et-ccd-callbacks, pull requests merged in 2024-04, with the labels that each got.

#1770 RET-4743 - Set notification with multiple ref
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/MultiplesSendNotificationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1770

#1752 RET-4913 - Update BF scheduled task
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/wa/BFActionsScheduledTasks.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/wa/BFActionsScheduledTasksTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1752

#1781 Merge branch 'master' into Rule-92_V2
  .nvmrc
  build.gradle
  charts/et-cos/Chart.yaml
  charts/et-cos/values.yaml
  infrastructure/database.tf
  infrastructure/main.tf
  infrastructure/state.tf
  package.json
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/MultiplesSendNotificationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PersistentQHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/MultiplesSendNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/wa/BFActionsScheduledTasks.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/MultipleNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDetailsGenerator.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/wa/BFActionsScheduledTasksTest.java
  src/test/resources/PreHearingDepositData.xlsx
  yarn.lock
Labels: ns:et, prd:et, rel:et-cos-pr-1781

#1753 RET-4294, RET-4557, RET-4909 - Referral changes
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CloseReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/UpdateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/ReferralTypeData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReferralService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/UpdateReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReferralServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1753

#1502 Ret 4296 - Fix status tags
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationServiceTest.java
Labels: ns:et, prd:et, destroy, rel:et-cos-pr-1502

#1786 Ret 4706 - Multiples - Enable 'Close a referral' Event
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CloseReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/CloseReferralMultiplesController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/CloseReferralMultiplesControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/ReplyToReferralMultiplesControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/ReferralsUtil.java
Labels: ns:et, prd:et, rel:et-cos-pr-1786

#1744 RET-4874 - Add documents with index
  .nvmrc
  build.gradle
  infrastructure/state.tf
  package.json
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/AddDocumentController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CloseReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/CloseReferralMultiplesController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentManagementService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/CloseReferralMultiplesControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/ReplyToReferralMultiplesControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentManagementServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/ReferralsUtil.java
  yarn.lock
Labels: ns:et, prd:et, enable_keep_helm, rel:et-cos-pr-1744, aat/no-changes

#1805 RET-4990: Hide rule92 answer on ECC notifications
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/TableMarkupConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MarkdownHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondentViewServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1805

#1816 RET-4715 - Batch send notifications
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/MultiplesSendNotificationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleUploadService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/MultiplesSendNotificationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/MultipleNotificationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1816

#1822 Update Sheffield mapping
  src/main/resources/venueAddressValues.yml
Labels: ns:et, prd:et, rel:et-cos-pr-1822

#1801 Rule-92 CUI
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseClaimantController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseClaimantControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1801

#1787 RET-4926: ResponseReceivedCounter for WA
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1787

#1837 RET-5013 - Tom's additional logic
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/casetransfer/CaseTransferSameCountryService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/casetransfer/CaseTransferSameCountryServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1837

#1839 RET-5017: Hearing details in Create Referral multiples controller
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/CreateReferralMultiplesController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/ReplyToReferralMultiplesController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/CreateReferralMultiplesControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/ReplyToReferralMultiplesControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1839

#1811 RET-4994
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentManagementService.java
Labels: ns:et, prd:et, enable_keep_helm, aat/no-changes, rel:et-cos-pr-1811

#1684 Ret 4281 new
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/AddDocumentController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentManagementService.java
  src/main/resources/application-dev.yaml
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/NoticeOfChangeControllerFunctionalTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/AddDocumentControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentManagementServiceTest.java
Labels: ns:et, prd:et, enable_keep_helm, no-changes, rel:et-cos-pr-1684

#1840 RET-5008 - Exclude ECC responses from claimant
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondentViewServiceTest.java
Labels: ns:et, prd:et, aat/no-changes, rel:et-cos-pr-1840

#1853 Fix stupid persistent springdoc issue that uses 1000x more CPU than it should
  src/main/resources/application.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-1853

#1857 RET-4985: Functional tests for Multiples
  Jenkinsfile_CNP
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/CloseReferralMultiplesController.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/BaseFunctionalTest.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/IdamTestApiRequests.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/NoticeOfChangeControllerFunctionalTest.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/model/CreateUser.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/multiples/CloseReferralMultiplesControllerFunctionalTest.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/multiples/CreateReferralMultiplesControllerFunctionalTest.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/multiples/ReplyToReferralMultiplesControllerFunctionalTest.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/multiples/SendNotificationMultiplesControllerFunctionalTest.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/multiples/UpdateReferralMultiplesControllerFunctionalTest.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/multiples/UploadDocumentMultiplesControllerFunctionalTest.java
  src/test/apiTest/resources/application.yaml
  src/test/resources/eventCreateMultiple.json
  src/test/resources/eventET1Vetting.json
  src/test/resources/eventInitiateCase.json
  src/test/resources/eventPreAcceptanceCase.json
Labels: ns:et, prd:et, rel:et-cos-pr-1857
