Repository hmcts/et-ccd-callbacks, pull requests merged in 2024-07, with the labels that each got.

#2062 Extend suppress until
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-2062

#2031 RET-5115
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2031

#2049 RET-5232: Added jurisdictions list
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UpdateDataModelBuilder.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleSingleMidEventValidationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UpdateDataModelBuilderTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleSingleMidEventValidationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2049

#2011 Jurisdiction Code updates
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/referencedata/JurisdictionCode.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/JurisdictionCodeTrackConstants.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationServiceTest.java
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-2011

#2070 RET-5247
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-2070

#2068 RET-5232: Fix for null jurisdictions
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UpdateDataModelBuilder.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleBatchUpdate3Service.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UpdateDataModelBuilderTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleBatchUpdate3ServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2068

#2071 Fix Claimant Pay
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et1ReppedHelper.java
Labels: ns:et, prd:et, enable_keep_helm, rel:et-cos-pr-2071

#2076 Changes for postgres integration tests
  src/test/integration/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/repository/EtCosPostgresqlContainer.java
Labels: ns:et, prd:et, rel:et-cos-pr-2076

#2075 RET-5232: Fix checkAnyChanged
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleBatchUpdate3Service.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleBatchUpdate3ServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2075

#2078 RET-0000: Fix NPE on confirmation on UpdateCases message
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/MultiplesSendNotificationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/MultipleNotificationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2078

#2082 Delete src/kubernetes directory
  src/kubernetes/config.aat.yaml
  src/kubernetes/config.saat.yaml
  src/kubernetes/deployment.template.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-2082

#1915 RET-5073
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/NotificationServiceConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseService.java
  src/main/resources/application.yaml
  src/test/apiTest/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1915

#2077 RET-5270
  build.gradle
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-2077

#2089 RET-5267: Allow Vetted and Submitted cases into a Multiple
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ExcelActionsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/CallbackRespHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MultiplesHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationMidEventValidationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ExcelActionsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MultiplesHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationMidEventValidationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2089

#2069 RET-5244
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/HearingDetailsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/IssueInitialConsiderationDirectionsWAController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseClaimantController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseRespondentReplyController.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3VettingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/HearingDetailsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/IssueInitialConsiderationDirectionsWAControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseClaimantControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseRespondentReplyControllerTest.java
Labels: ns:et, prd:et, enable_keep_helm, rel:et-cos-pr-2069

#2096 RET-5267: Add Feature Flag
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationMidEventValidationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationMidEventValidationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2096

#2036 RET 5188
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/TSEConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ClaimantTellSomethingElseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseClaimantController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/TseApplicationData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/TseApplicationDocument.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ClaimantTellSomethingElseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/RespondentTellSomethingElseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ClaimantTellSomethingElseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/RespondentTSEApplicationTypeData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/TSEApplicationTypeData.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ClaimantTellSomethingElseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ClaimantTellSomethingElseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ClaimantTellSomethingElseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseServiceTest.java
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-2036

#2100 Update Et1ReppedHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et1ReppedHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-2100

#2101 RET-5282: Initialised CellStyle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelCreationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelCreationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2101

#2102 Refactor claimant docs to look at new doc naming
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2102

#2083 RET-5269
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/NotificationServiceConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3NotificationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3NotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingService.java
  src/main/resources/application.yaml
  src/test/apiTest/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NotificationHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingServiceTest.java
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-2083

#2099 Ret 5192
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/TSEConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ClaimantTellSomethingElseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ClaimantTellSomethingElseServiceTest.java
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-2099

#2081 RET-5243
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Constants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DigitalCaseFileService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DigitalCaseFileServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2081

#2065 To be merged 15 Jul - RET-5240
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1ReppedService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1ReppedServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2065

#2112 Fix last fortify issue
  src/cftlib/resources/compose/docker-compose.yml
Labels: ns:et, prd:et, rel:et-cos-pr-2112

#2107 added support for rest of the claimant applications
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/TSEConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ClaimantTellSomethingElseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ClaimantTellSomethingElseServiceTest.java
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-2107

#1983 RET-4856
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/PdfBoxService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormHeaderMapper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormMapper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/PdfBoxServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormHeaderMapperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormMapperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormTestConstants.java
Labels: ns:et, prd:et, rel:et-cos-pr-1983

#2129 Update InvalidCharacterCheck.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/letters/InvalidCharacterCheck.java
Labels: ns:et, prd:et, rel:et-cos-pr-2129

#2133 Run nightly master on cron
  Jenkinsfile_nightly
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-2133

#2142 RET-5326
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/DocumentGenerationController.java
Labels: ns:et, prd:et, rel:et-cos-pr-2142

#2141 NoC fields
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/tasks/NoticeOfChangeFieldsTask.java
  src/main/resources/application.yaml
  src/test/apiTest/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/tasks/NoticeOfChangeFieldsTaskTest.java
Labels: ns:et, prd:et, enable_keep_helm, rel:et-cos-pr-2141

#2154 Update to cron job
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/tasks/NoticeOfChangeFieldsTask.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/tasks/NoticeOfChangeFieldsTaskTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2154
