Repository hmcts/et-ccd-callbacks, pull requests merged in 2024-08, with the labels that each got.

#2147 RET-5329
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/ET1ReppedConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et1ReppedHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1ReppedControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et1ReppedHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2147

#2159 Add trailing space
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormConstants.java
Labels: ns:et, prd:et, rel:et-cos-pr-2159

#2162 Change Java version in readme
  README.md
Labels: ns:et, prd:et, rel:et-cos-pr-2162

#2166 RET-5337
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/PartySpacingTask.java
  src/main/resources/application.yaml
  src/test/apiTest/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/tasks/PartySpacingTaskTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2166

#2176 Add state filter to update only live cases
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/tasks/PartySpacingTask.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/tasks/PartySpacingTaskTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2176

#2201 RET-5339 - Fix perf test issues
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ExcelReportHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/Constants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/BfExcelReportService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ClaimsByHearingVenueExcelReportCreationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelCreationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleScheduleService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/NotificationScheduleService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/NotificationsExcelReportService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ExcelReportHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/BfExcelReportServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ClaimsByHearingVenueExcelReportCreationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelCreationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleScheduleServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/NotificationsExcelReportServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2201

#2206 RET-5366 - Optimise performance
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/BulkHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Constants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et1ReppedHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/multiples/MultipleNotificationsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkCreationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkUpdateService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/NotificationScheduleService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/NotificationsExcelReportService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/LoggingUtil.java
  src/main/resources/application.yaml
  src/test/apiTest/resources/application.yaml
  src/test/functional/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/multiples/MultipleNotificationsHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/NotificationScheduleServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/SendNotificationUtil.java
Labels: ns:et, prd:et, rel:et-cos-pr-2206

#2180 RET-5353
  build.gradle
  docs/cftlib.md
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/CftlibConfig.java
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/RolesConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CcdCaseAssignment.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1ReppedService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseCreationForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CcdCaseAssignmentTest.java
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-2180

#2215 RET-5370
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2215

#2148 CR - Rule92 Email notifications
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/TSEConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ClaimantTellSomethingElseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ClaimantTellSomethingElseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ClaimantTellSomethingElseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
  src/main/resources/application.yaml
  src/test/apiTest/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ClaimantTellSomethingElseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ClaimantTellSomethingElseServiceTest.java
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-2148

#2128 Harpreet POC - Ret 4277
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1ReppedController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1ReppedService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1SubmissionService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleService.java
  src/main/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1ReppedControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1ReppedServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1SubmissionServiceTest.java
  src/test/resources/citizenCaseData.json
  src/test/resources/et1ReppedDraftStillWorking.json
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-2128

#2246 Nightly dev
  Jenkinsfile_nightly
  package.json
  src/test/end-to-end/data/commonConfig.json
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/pages/IDAM/signIn.js
  src/test/end-to-end/pages/amendCaseDetails/amendCaseDetails.js
  src/test/end-to-end/pages/amendCaseDetails/amendCaseDetailsWithCasePosition.js
  src/test/end-to-end/pages/amendClaimantDetails/helper/claimantHearingPreferences.js
  src/test/end-to-end/pages/createCase/caseDate.js
  src/test/end-to-end/pages/createCase/caseHearingPref.js
  src/test/end-to-end/pages/nextStep/nextStep.js
  src/test/end-to-end/paths/moveAcceptedCaseToCaseCloseStateErrorCheck.js
  src/test/end-to-end/paths/verifyCaseListHearing.js
  src/test/end-to-end/paths/verifyCreateReport.js
Labels: ns:et, prd:et, rel:et-cos-pr-2246

#2254 Enable latest XUI without WA
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-2254
