Repository hmcts/et-ccd-callbacks, pull requests merged in 2024-03, with the labels that each got.

#1662 RET-4733: Update CMC to use new order
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/BundlesRespondentControllerFunctionalTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1662

#1671 RET-4250: Add Case Stayed option to batch update
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MultiplesHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UpdateDataModelBuilder.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UpdateDataModelBuilderTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1671

#1579 RET-4702
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1579

#1701 RET-0000: Added methods to TornadoService to enable reducing tight coupling
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/TornadoDocument.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1701

#1702 RET-0000: Added request interceptor for token verify service
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/config/WebConfig.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/config/interceptors/RequestInterceptor.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/config/RequestInterceptorTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/BaseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/BulkActionsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/BundlesRespondentControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseFlagsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferMultiplesControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/DigitalCaseFileControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/DocumentGenerationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3NotificationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3VettingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ExcelActionsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/GlobalSearchDataMigrationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/HearingUnavailabilityControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/IssueInitialConsiderationDirectionsWAControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/LegalRepDocumentsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListHearingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListingGenerationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/MultipleDocGenerationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PersistentQueueActionsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseViewNotificationsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReferenceDataControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/SendNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdmReplyControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdminControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseRespondentReplyControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseViewApplicationsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/UploadDocumentControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/filelocation/FileLocationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/staff/StaffImportControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/venues/VenueImportControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1702

#1703 Renovate merge before midday
  renovate.json
Labels: ns:et, prd:et, rel:et-cos-pr-1703

#1709 RET-0000: Adding protected to BaseControllerTest setUp for overriding in other packages
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/BaseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/BundlesRespondentControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseFlagsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseTransferControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/DigitalCaseFileControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3NotificationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3VettingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/HearingUnavailabilityControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/IssueInitialConsiderationDirectionsWAControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/LegalRepDocumentsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseViewNotificationsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondentTellSomethingElseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/SendNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdmReplyControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdminControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseRespondentReplyControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseViewApplicationsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/UploadDocumentControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1709

#1704 Update venue addresses
  src/main/resources/db/dev/V003.1__DevReferenceData.sql
  src/main/resources/venueAddressValues.yml
Labels: ns:et, prd:et, rel:et-cos-pr-1704

#1480 RET-4123
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/main/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1480, no-changes

#1699 Ret 4687 - Send Notification from Multiple
  .gitignore
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/MultiplesSendNotificationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PersistentQHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleHelperService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/MultiplesSendNotificationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/MultiplesSendNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MultipleUtil.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/MultipleNotificationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1699

#1724 RET-4699
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/MultipleUploadDocumentController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/MultipleUploadDocumentControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1724

#1747 Test AppInsights upgrade
  Dockerfile
  charts/et-cos/values.preview.template.yaml
Labels: ns:et, prd:et, enable_keep_helm, rel:et-cos-pr-1747

#1745 RET-4899
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseClaimantController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
Labels: ns:et, prd:et, no-changes, rel:et-cos-pr-1745

#1746 RET - 4711 - Send Notification to all
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/MultiplesSendNotificationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PersistentQHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/MultiplesSendNotificationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/MultipleNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/CaseDetailsGenerator.java
  src/test/resources/PreHearingDepositData.xlsx
Labels: ns:et, prd:et, rel:et-cos-pr-1746

#1748 RET-4911: Reset SelectedReferral for when new Referral is being created.
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1748
