Repository hmcts/et-ccd-callbacks, pull requests merged in 2024-06, with the labels that each got.

#1972 Manchester expansion
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1ReppedService.java
Labels: ns:et, prd:et, rel:et-cos-pr-1972

#1978 Leeds Westgate change
  src/main/resources/defaults.yml
Labels: ns:et, prd:et, rel:et-cos-pr-1978

#1971 RET-5118 - Set case management location on multiple
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkUpdateService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementLocationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/casetransfer/MultipleTransferSameCountryService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/casetransfer/MultipleTransferSameCountryServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1971

#1985 RET-5178: Added more missing role assignements from ecm-ccd-docker
  src/cftlib/resources/roleAssignment.json
Labels: ns:et, prd:et, rel:et-cos-pr-1985

#1988 Fix unassigned office casetype bug
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/AcasCertificateController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/AcasService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1ReppedService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/AcasCertificateControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/AcasServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1988

#1979 RET-5024
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CloseReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MarkdownHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
Labels: ns:et, prd:et, enable_keep_helm, aat/no-changes, prod/no-changes, rel:et-cos-pr-1979

#1878 RET-4774
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/BundlesRespondentController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BundlesRespondentService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/BundlesRespondentControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BundlesRespondentServiceTest.java
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-1878

#1993 RET-5204
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et1VettingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3VettingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/letters/InvalidCharacterCheck.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1ReppedService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/letters/InvalidCharacterCheckTest.java
  src/test/resources/et3ResponseDocument.json
Labels: ns:et, prd:et, rel:et-cos-pr-1993

#2004 Another disallowed char
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/letters/InvalidCharacterCheck.java
Labels: ns:et, prd:et, rel:et-cos-pr-2004

#2003 RET-5194
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-2003

#2005 RET-5218
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/RespondentTellSomethingElseData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/RespondentTellSomethingElseHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/RespondentTellSomethingElseHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2005

#2012 Update build.gradle
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-2012

#2013 transferred case ref retrieval added
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseRetrievalForCaseWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseRetrievalForCaseWorkerServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2013

#2002 To be merged 17/06/2024 - RET-5208
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1ReppedService.java
Labels: ns:et, prd:et, rel:et-cos-pr-2002

#2015 RET-5187: Transfer LRs along with Multiple
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleBatchUpdate2Service.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleHelperService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/MultipleReferenceService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/MultipleReferenceServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleBatchUpdate2ServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2015

#2025 RET-5202 - Bump et-data-model
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-2025

#2035 NPE bug fix
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
Labels: ns:et, prd:et, rel:et-cos-pr-2035

#2024 RET-5205: Remove sub-case from Multiple
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ExcelActionsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MultiplesHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleAmendCaseIdsService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleAmendService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleBatchUpdate2Service.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationMidEventValidationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ExcelActionsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MultiplesHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleAmendCaseIdsServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleAmendServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationMidEventValidationServiceTest.java
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-2024

#2029 RET-5201: Applying Legalrep access to newly created multiple
  src/cftlib/resources/compose/mocks/wiremock/__files/prd/users.json
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ExcelActionsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/rdprofessional/OrganisationClient.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleBatchUpdate2Service.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleUpdateService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/MultipleReferenceService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleBatchUpdate2ServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleUpdateServiceTest.java
  src/test/resources/PreHearingDepositData.xlsx
Labels: ns:et, prd:et, rel:et-cos-pr-2029

#2046 Fix ClaimantWorkAddress question
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et1ReppedHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-2046

#1956 Trim respondentName to remove trailing spaces
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3VettingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3VettingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1956

#2047 RET-0000: Fix NPE when creating a multiple with a single that has no legalreps
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleCreationServiceTest.java
Labels: ns:et, prd:et, enable_keep_helm, rel:et-cos-pr-2047

#1918 RET-5054
  bin/docker-clean.sh
  bin/pull-cftlib-images.sh
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/exceptions/GenericServiceException.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/exceptions/VerifyTokenServiceException.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/PdfBoxService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/PdfBoxServiceConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormAcasMapper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormClaimantMapper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormDisabilityMapper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormEarningsAndBenefitsMapper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormEmployerContractClaimMapper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormEmploymentMapper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormHeaderMapper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormMapper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormRepresentativeMapper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormRespondentMapper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormResponseMapper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/util/ET3FormUtil.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/util/PdfBoxServiceUtil.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/LoggingUtil.java
  src/main/resources/CY_ET3_0224.pdf
  src/main/resources/ET3_0224.pdf
  src/main/resources/application.yaml
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/Et3ResponseControllerFunctionalTest.java
  src/test/apiTest/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/PdfBoxServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/PdfBoxServiceTestConstants.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormAcasMapperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormClaimantMapperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormDisabilityMapperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormEarningsAndBenefitsMapperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormEmployerContractClaimMapperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormEmploymentMapperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormHeaderMapperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormMapperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormRepresentativeMapperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormRespondentMapperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormResponseMapperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/ET3FormTestConstants.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/util/ET3FormTestUtil.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/et3/util/ET3FormUtilTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/pdf/util/PdfBoxServiceUtilTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/ResourceLoader.java
  src/test/resources/et3FormCaseData.json
Labels: ns:et, prd:et, enable_keep_helm, rel:et-cos-pr-1918

#2030 RET-5206 - Update notifications extract
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PseRespondToTribunalController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/multiples/NotificationGroup.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/multiples/MultipleNotificationsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/NotificationsExcelReportService.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/multiples/SendNotificationMultiplesControllerFunctionalTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/multiples/MultipleNotificationsHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/SendNotificationUtil.java
  src/test/resources/PreHearingDepositData.xlsx
Labels: ns:et, prd:et, rel:et-cos-pr-2030

#2054 Update Et1ReppedHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et1ReppedHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-2054

#2053 RET-5255: Use latest Release of et-common
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-2053

#2050 RET-5246 and PMD
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
Labels: ns:et, prd:et, rel:et-cos-pr-2050

#2057 Replace colon in file name with space
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/letters/InvalidCharacterCheck.java
Labels: ns:et, prd:et, rel:et-cos-pr-2057
