Repository hmcts/et-ccd-callbacks, pull requests merged in 2024-05, with the labels that each got.

#1884 Preview mem limits
  charts/et-cos/values.preview.template.yaml
Labels: ns:et, prd:et, rel:et-cos-pr-1884

#1860 RET-5010: Update Data Model
  build.gradle
Labels: ns:et, prd:et, aat/no-changes, rel:et-cos-pr-1860, prod/no-changes

#1843 Ret 5023
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/casetransfer/CaseTransferSameCountryService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/casetransfer/CaseTransferSameCountryServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1843

#1789 RET-4632
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/NotificationServiceConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EmailService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
Labels: ns:et, prd:et, enable_keep_helm, aat/no-changes, rel:et-cos-pr-1789

#1883 Ret 4732 - Add notifications extract
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/ExtractNotificationsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/multiples/NotificationGroup.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Constants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DynamicListHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et1VettingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/InitialConsiderationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MultiplesScheduleHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/multiples/MultipleNotificationsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/JudgmentValidationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ScheduleCreationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/SingleCasesReadingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/NotificationScheduleService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/NotificationsExcelReportService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/tasks/NotificationScheduleCallable.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/PseViewNotificationsControllerFunctionalTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/ExtractNotificationsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MultipleUtil.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/multiples/MultipleNotificationsHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/casescompleted/CaseCompletedReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleScheduleServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/SingleCasesReadingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/NotificationScheduleServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/NotificationsExcelReportServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/SendNotificationUtil.java
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-1883

#1891 RET-5037: Showing respond button for ECC only notifications that require it
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
Labels: ns:et, prd:et, rel:et-cos-pr-1891

#1903 RET-5036: Sending email on Create/Reply referral (multiples)
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/CreateReferralMultiplesController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/ReplyToReferralMultiplesController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReferralService.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/multiples/CreateReferralMultiplesControllerFunctionalTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReferralServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1903

#1902 RET-5057
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentGenerationService.java
Labels: ns:et, prd:et, rel:et-cos-pr-1902

#1882 RET-4988
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/BundlesRespondentController.java
Labels: ns:et, prd:et, rel:et-cos-pr-1882

#1909 RET-5053 - Add case notes feature
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/CaseNotesController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/CaseNotesService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/CaseNotesControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/CaseNotesServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1909

#1886 RET-5033
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/NotificationServiceConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseService.java
  src/main/resources/application.yaml
  src/test/apiTest/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1886

#1917 Update Jenkinsfile_nightly
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-cos-pr-1917

#1901 Transfer case link update
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Constants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseRetrievalForCaseWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReportDocTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseRetrievalForCaseWorkerServiceTest.java
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, do not merge, rel:et-cos-pr-1901

#1897 Ret 4678 - Legal rep access to multiple
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/NoticeOfChangeController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MultiplesHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseLookupService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CcdCaseAssignment.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleBatchUpdate2Service.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleBatchUpdate3Service.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleUpdateService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CcdCaseAssignmentTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleBatchUpdate2ServiceTest.java
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-1897

#1933 Sonar and PMD fixes 1
  build.gradle
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CloseReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/UpdateReferralControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/CloseReferralMultiplesControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/CreateReferralMultiplesControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/ReplyToReferralMultiplesControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/UpdateReferralMultiplesControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/BulkHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DynamicListHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3VettingHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingVenueHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReportHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/casescompleted/SessionDaysTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/respondentsreport/RespondentReportElasticSearchQueryTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/servingclaims/ServingClaimsReportTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BundlesRespondentServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseCloseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseLinksEmailServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementLocationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ClerkServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DigitalCaseFileServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PrintHearingListServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/FileLocationFixedListSheetImporterTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/FileLocationRowHandlerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/fixedlistsheetreader/VenueFixedListSheetImporterTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/venues/VenueImportServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/casetransfer/CaseTransferDifferentCountryServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/casetransfer/CaseTransferSameCountryServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/casetransfer/CaseTransferUtilsTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/BfExcelReportServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ClaimsByHearingVenueExcelReportCreationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/referencedata/selection/CourtWorkerSelectionServiceTest.java
  src/test/utils/java/uk/gov/hmcts/ethos/utils/CaseDataBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-1933

#1935 RET-4678: Update Release Feature Flag
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CcdCaseAssignment.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CcdCaseAssignmentTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1935

#1941 Update data model and data files
  build.gradle
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/allocatehearing/RoomSelectionServiceTest.java
  src/test/resources/exampleListingSingleV1.json
  src/test/resources/exampleListingSingleV2.json
  src/test/resources/exampleV1.json
  src/test/resources/exampleV2.json
Labels: ns:et, prd:et, rel:et-cos-pr-1941

#1942 Et1 doc cron
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1ReppedController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et1ReppedHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/tasks/Et1DocumentGenerationTask.java
  src/main/resources/application.yaml
  src/test/apiTest/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1ReppedControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/tasks/Et1DocumentGenerationTaskTest.java
  src/test/resources/et1GenerateDocTask.json
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-1942

#1940 RET-4762: Added nextListedDate to Multiple
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CcdCaseAssignment.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleHelperService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleHelperServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-1940

#1810 Ret 4523
  build.gradle
  config/owasp/suppressions.xml
  src/cftlib/resources/compose/mocks/wiremock/__files/prd/organisationResponse.json
  src/cftlib/resources/compose/mocks/wiremock/mappings/prd/getOrganisationByUserId.json
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/ET1ReppedConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1ReppedController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/ClaimantSolicitorRole.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ClaimantHearingPreferencesValidator.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Constants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et1ReppedHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/rdprofessional/OrganisationClient.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/casesourcelocalreport/CaseSourceLocalReport.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/AcasService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/BulkCreationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CcdCaseAssignment.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1ReppedService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EventValidationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SingleReferenceService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TribunalOfficesService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/VerifyTokenService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/staff/JudgeService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/tasks/Et1DocumentGenerationTask.java
  src/main/resources/application.yaml
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/BaseFunctionalTest.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/Et1ReppedControllerFunctionalTest.java
  src/test/apiTest/resources/application.yaml
  src/test/apiTest/resources/et1Repped.json
  src/test/end-to-end/pages/createCase/caseResp.js
  src/test/end-to-end/pages/createCase/caseRespondents.json
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1ReppedControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et1ReppedHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/AcasServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CcdCaseAssignmentTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1ReppedServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TribunalOfficeEpimmServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TribunalOfficeServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/tasks/Et1DocumentGenerationTaskTest.java
  src/test/resources/et1GenerateDocTask.json
  src/test/resources/et1ReppedDraftNoLongerWorking.json
  src/test/resources/et1ReppedDraftStillWorking.json
  src/test/resources/et1ReppedDraftWorkingNoticePeriod.json
  src/test/utils/java/uk/gov/hmcts/ethos/utils/CaseDataBuilder.java
Labels: ns:et, prd:et, enable_keep_helm, aat/no-changes, rel:et-cos-pr-1810, prod/no-changes

#1970 RET-5178: Fix functional tests on CFTLib
  build.gradle
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/CftlibConfig.java
  src/cftlib/resources/roleAssignment.json
Labels: ns:et, prd:et, rel:et-cos-pr-1970
