Repository hmcts/et-ccd-callbacks, pull requests merged in 2024-10, with the labels that each got.

#2339 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-2339

#2345 et-data-model bump
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-2345

#2331 Claimant rep notifications
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/ET1ReppedConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/LegalRepDocumentConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/notifications/admin/RespondNotificationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/notifications/admin/SendNotificationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/notifications/claimant/RespondToNotificationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/notifications/claimant/ViewNotificationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/notifications/respondent/PseRespondToTribunalController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/notifications/respondent/PseRespondentViewController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/notifications/respondent/PseViewNotificationsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MarkdownHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EmailService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3NotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ProvideSomethingElseViewService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondentViewService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingService.java
  src/main/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/notifications/admin/RespondNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/notifications/admin/SendNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/notifications/claimant/RespondToNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/notifications/claimant/ViewNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/notifications/respondent/PseRespondToTribunalControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/notifications/respondent/PseRespondentViewControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/notifications/respondent/PseViewNotificationsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NotificationHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseLinksEmailServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ProvideSomethingElseViewServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdminServiceTest.java
  src/test/utils/java/uk/gov/hmcts/ethos/utils/CaseDataBuilder.java
Labels: ns:et, prd:et, rel:et-cos-pr-2331

#2338 RET-5403
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2338

#2365 bump et-common
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-2365

#2382 Fix NPE
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DigitalCaseFileService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DigitalCaseFileServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2382
