Repository hmcts/et-ccd-callbacks, pull requests merged in 2024-09, with the labels that each got.

#2253 Fix pmdTest issues
  build.gradle
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/SolicitorRoleTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/hearingstojudgments/HearingsToJudgmentsReportDataTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/memberdays/MemberDaysReportDocTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/nochangeincurrentposition/NoPositionChangeReportDataTests.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1SubmissionServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/VenueAddressesServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleBatchUpdate2ServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2253

#2222 RET-5372 - Complete notification extract asynchronously
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/ExtractNotificationsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/SingleCasesReadingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/NotificationScheduleService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/NotificationsExcelReportService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/NotificationScheduleServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/NotificationsExcelReportServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2222

#2257 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-2257

#2275 Update renovate.json
  renovate.json
Labels: ns:et, prd:et, rel:et-cos-pr-2275

#2272 RET-5351
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/LegalRepDocumentConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/LegalRepDocumentsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/LegalRepDocumentsHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/MarkdownHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/LegalRepDocumentsControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DocumentHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/LegalRepDocumentsHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/DocumentFixtures.java
Labels: ns:et, prd:et, rel:et-cos-pr-2272

#2301 Make life easier for Admin data import
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/JudgeRowHandler.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/JudgeRowHandlerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2301

#2308 Ref Data empty cell
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/JudgeRowHandler.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/admin/excelimport/rowreader/JudgeRowHandlerTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2308

#2284 RET-5396
  build.gradle
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/CftlibConfig.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseAccessController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseAccessService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CcdCaseAssignment.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseAccessControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseAccessServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CcdCaseAssignmentTest.java
Labels: ns:et, prd:et, enable_keep_helm, rel:et-cos-pr-2284

#2325 judge's draft and sign
  build.gradle
Labels: ns:et, prd:et, rel:et-cos-pr-2325

#2287 RET-5389
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/referencedata/JurisdictionCode.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/JurisdictionCodeTrackConstants.java
  src/test/resources/PreHearingDepositData.xlsx
Labels: ns:et, prd:et, rel:et-cos-pr-2287
