Repository hmcts/et-ccd-callbacks, pull requests merged in 2024-11, with the labels that each got.

#2390 Ret 5437
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationServiceTest.java
  src/test/resources/PreHearingDepositData.xlsx
Labels: ns:et, prd:et, rel:et-cos-pr-2390

#2394 Add ECM Roles to make life easier
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/CftlibConfig.java
  src/cftlib/java/uk/gov/hmcts/ethos/replacement/docmosis/RolesConstants.java
Labels: ns:et, prd:et, rel:et-cos-pr-2394

#2396 Prod NPEs fix jur code validation
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2396

#2392 RET-5462, RET-5436 & RET-5437
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/HearingDetailsController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/hearingdetails/HearingDetailsService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/hearingdetails/HearingDetailServiceTest.java
  src/test/resources/PreHearingDepositData.xlsx
Labels: ns:et, prd:et, rel:et-cos-pr-2392

#2406 RET-5444
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/InitialConsiderationHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/InitialConsiderationHelperTest.java
Labels: ns:et, prd:et, enable_keep_helm, rel:et-cos-pr-2406

#2407 Ret 5445
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2407

#2408 Ret 5446
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/InitialConsiderationConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2408

#2414 IC Scotland mappings improved + clear hidden data
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/InitialConsiderationConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2414

#2403 Fix binary urls on applications
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseAdmReplyHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/DocumentUtil.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseRespondentReplyServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2403

#2417 IC multiple doc upload
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2417

#2402 data model bump
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/InitialConsiderationConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/DigitalCaseFileController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/UploadDocumentController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/documents/InitialConsiderationData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/InitialConsiderationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/InitialConsiderationHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2402
