Repository hmcts/et-ccd-callbacks, pull requests merged in 2025-04, with the labels that each got.

#2620 Further changes
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
Labels: ns:et, prd:et, rel:et-cos-pr-2620

#2623 extend admin reply to support respondents
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseAdmReplyServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2623

#2626 RET-5752
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/InitialConsiderationConstants.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2626

#2632 RET-5722
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-2632

#2635 RET-5722
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:et, prd:et, rel:et-cos-pr-2635

#2636 Update ReferralHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
Labels: ns:et, prd:et, rel:et-cos-pr-2636

#2639 ET3Vetting address concatenation causing symbols to appear
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3VettingHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3VettingHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2639

#2638 RET-5754
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseService.java
Labels: ns:et, prd:et, enable_keep_helm, rel:et-cos-pr-2638
