Repository hmcts/et-ccd-callbacks, pull requests merged in 2025-01, with the labels that each got.

#2453 RET-5434
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/BulkHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/BulkHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2453

#2473 Rule Changes
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/InitialConsiderationConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1VettingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/InitialConsiderationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/UpdateReferralController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/CreateReferralMultiplesController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/multiples/UpdateReferralMultiplesController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/InitialConsiderationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ListingHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/InitialConsiderationHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2473

#2476 et-common bump
  build.gradle
Labels: ns:et, prd:et

#2488 disable test
  Jenkinsfile_nightly
Labels: ns:et, prd:et

#2489 ReferralChange
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
Labels: ns:et, prd:et

#2493 et-data-model bump
  build.gradle
Labels: ns:et, prd:et

#2502 Update letters to add BF, Claim Served Date and ET3 Due Date
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DocumentGenerationService.java
Labels: ns:et, prd:et

#2483 DCF Changes
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/client/BundleApiClient.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/DigitalCaseFileController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DigitalCaseFileHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UploadDocumentHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DigitalCaseFileService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/MultiplesDigitalCaseFileService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/DigitalCaseFileControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/DigitalCaseFileHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DigitalCaseFileServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/MultiplesDigitalCaseFileServiceTest.java
  src/test/resources/stitchBundleRequest.json
Labels: ns:et, prd:et
