Repository hmcts/et-ccd-callbacks, pull requests merged in 2025-03, with the labels that each got.

#2588 update report name
  Jenkinsfile_CNP
Labels: ns:et, prd:et, rel:et-cos-pr-2588

#2594 Update chars to replace
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/letters/InvalidCharacterCheck.java
Labels: ns:et, prd:et, rel:et-cos-pr-2594

#2587 RET-247
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdminController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/TseAdminControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PseRespondToTribunalServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2587

#2595 Set up xui-e2e-tests as part of CCD-Callback PR & Master pipeline
  Jenkinsfile_CNP
  bin/pull-latest-e2e-tests.sh
  package.json
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-2595

#2600 extend email addresses to support respondents
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ClaimantTellSomethingElseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ClaimantTellSomethingElseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EmailService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseClaimantRepReplyService.java
  src/main/resources/application.yaml
  src/test/apiTest/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ClaimantTellSomethingElseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseClaimantRepReplyServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2600

#2579 ECM to RET rollback
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/config/CcdClientConfiguration.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/MigrationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EcmMigrationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/MigrationControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EcmMigrationServiceTest.java
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-2579
