Repository hmcts/et-ccd-callbacks, pull requests merged in 2025-08, with the labels that each got.

#2744 RET-5897
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocClaimantRepresentativeService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeService.java
Labels: ns:et, prd:et, rel:et-cos-pr-2744

#2709 RET-5425
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RefreshSharedUsersController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RefreshSharedUsersService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RefreshSharedUsersServiceTest.java
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-2709

#2755 RET-5520
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingServiceTest.java
  src/test/resources/midServingCaseDetailsTest.json
Labels: ns:et, prd:et, rel:et-cos-pr-2755

#2756 RET-5422
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/ET3ResponseConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1ReppedController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et1ReppedHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1ReppedService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/MyHmctsService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/AddressUtils.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et1ReppedControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3ResponseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et1ReppedHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1ReppedServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1SubmissionServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3ResponseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/MyHmctsServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/AddressUtilsTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2756
