Repository hmcts/et-ccd-callbacks, pull requests merged in 2025-09, with the labels that each got.

#2819 RET-5967
  src/main/resources/defaults.yml
Labels: ns:et, prd:et, rel:et-cos-pr-2819

#2818 Amend add delete claimant rep
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/AddAmendClaimantRepresentativeController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocClaimantHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/AddAmendClaimantRepresentativeService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocClaimantRepresentativeService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/AddAmendClaimantRepresentativeControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/AddAmendClaimantRepresentativeServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocClaimantRepresentativeServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeServiceTest.java
Labels: ns:et, prd:et, aat/no-changes, rel:et-cos-pr-2818

#2830 give user access to case
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/AccountIdByEmailResponse.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/idam/IdamApi.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/rdprofessional/OrganisationClient.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocClaimantRepresentativeService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/UserIdamService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocClaimantRepresentativeServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TornadoServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/UserIdamServiceTest.java
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-2830

#2820 Spring Caching
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/DocmosisApplication.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/AdminUserService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeService.java
  src/main/resources/application.yaml
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/BaseFunctionalTest.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/config/TestCacheConfig.java
  src/test/apiTest/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/AdminUserIdamServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/AdminUserServiceCachingTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2820

#2840 RET-5983
  README.md
  bin/tasks/BatchReconfigurationTask.sh
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/wa/BatchReconfigurationTask.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/wa/BatchReconfigurationTaskTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2840

#2843 Ret 5257 with task runner
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/wa/expiredbftask/WaTaskCreationCronForExpiredBfActions.java
Labels: ns:et, prd:et, rel:et-cos-pr-2843

#2857 Shared list emails - claimant apps
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/applications/claimant/ClaimantTellSomethingElseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/applications/claimant/TseClaimantRepReplyController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/applications/ClaimantTellSomethingElseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EmailNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/applications/admin/TseAdmReplyService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/applications/claimant/ClaimantTellSomethingElseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/applications/claimant/TseClaimantRepReplyService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/applications/claimant/ClaimantTellSomethingElseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/applications/claimant/TseClaimantRepReplyControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/applications/admin/TseAdmReplyServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/applications/claimant/ClaimantTellSomethingElseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/applications/claimant/TseClaimantRepReplyServiceTest.java
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-2857

#2859 bf action search time span is set to a moving 90 days
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/wa/expiredbftask/WaTaskCreationCronForExpiredBfActions.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/wa/WaTaskCreationCronForExpiredBfActionsTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2859

#2866 ECC - Create BF for Notice of ECC notification
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/notifications/admin/SendNotificationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationServiceTest.java
Labels: aat/no-changes, prod/no-changes

#2860 Shared list emails - respondent applications
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/NotificationServiceConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/applications/respondent/RespondentTellSomethingElseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseAccessService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EmailNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/applications/respondent/RespondentTellSomethingElseService.java
  src/test/apiTest/java/uk/gov/hmcts/ethos/replacement/apitest/RespondentTellSomethingElseControllerFunctionalTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/applications/respondent/RespondentTellSomethingElseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseAccessServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/applications/respondent/RespondentTellSomethingElseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2860

#2844 RET-3755
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2844

#2858 RET-5613
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2858

#2871 RET-6006
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/NOCConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Constants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CcdCaseAssignment.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocCcdService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocClaimantRepresentativeService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/OrganisationUtils.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/RespondentUtils.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocCcdServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocClaimantRepresentativeServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/OrganisationUtilsTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/RespondentUtilsTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2871

#2868 RET-6003
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HearingsHelperTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2868
