Repository hmcts/et-ccd-callbacks, pull requests merged in 2025-05, with the labels that each got.

#2646 Dependency Update
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ClaimantTellSomethingElseService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/TseHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ClaimantTellSomethingElseServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/RespondentTellSomethingElseServiceTest.java
Labels: ns:et, prd:et

#2647 missing_tests
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2647

#2641 RET-5293
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
Labels: ns:et, prd:et, enable_keep_helm, rel:et-cos-pr-2641

#2637 RET-5764
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/AcasCertificateController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/AcasService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1SubmissionService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/tasks/AcasCertificateTask.java
  src/main/resources/application.yaml
  src/test/apiTest/resources/application.yaml
  src/test/functional/resources/application.yaml
  src/test/integration/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/AcasServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1SubmissionServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/tasks/AcasCertificateTaskTest.java
  src/test/resources/et1GenerateDocTask.json
Labels: ns:et, prd:et, enable_keep_helm, rel:et-cos-pr-2637

#2645 RET-5784 - Implement fix - Scottish Cause List
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/Constants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingService.java
Labels: ns:et, prd:et, rel:et-cos-pr-2645

#2648 RET-5809
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/InitialConsiderationConstants.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/JurisdictionCodeHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/InitialConsiderationServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2648
