Repository hmcts/et-ccd-callbacks, pull requests merged in 2025-07, with the labels that each got.

#2687 RET-5850
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ET1ServingControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ServingServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2687

#2691 Update HearingDetailService to handle null values for hearing details
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/hearingdetails/HearingDetailsService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/hearings/hearingdetails/HearingDetailServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2691

#2696 RET-5624
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/NoticeOfChangeController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ClaimantTellSomethingElseHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NotificationHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseAccessService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeService.java
  src/main/resources/application.yaml
  src/test/apiTest/resources/application.yaml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/NoticeOfChangeControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/HelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/NocNotificationHelperTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/NocRespondentRepresentativeServiceTest.java
  src/test/resources/PreHearingDepositData.xlsx
Labels: ns:et, prd:et, aat/no-changes, prod/no-changes, rel:et-cos-pr-2696

#2716 Refactor vexationCheck method to use _source to help improve performance
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1SubmissionService.java
Labels: ns:et, prd:et, rel:et-cos-pr-2716

#2708 fix email personalisations
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
Labels: ns:et, prd:et, enable_keep_helm, aat/no-changes, prod/no-changes, rel:et-cos-pr-2708

#2710 RET-2699
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PreAcceptanceCaseController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PreAcceptanceCaseService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/PreAcceptanceCaseControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/PreAcceptanceCaseServiceTest.java
Labels: ns:et, prd:et, rel:et-cos-pr-2710
